#!/usr/bin/env bash
#
# An SSH server on the build host for BebboSSH to connect to.
#
#   tests/bebbossh/sshd.sh {start|stop|status|knownhosts}
#
# FS-UAE's SLIRP puts the HOST at 10.0.2.2, so an sshd on this machine is the
# shortest path to "does bebboscp move a file".  This starts one that touches
# nothing outside build/bebbossh-test/:
#
#   * port 2223, so neither the system's sshd nor clients/dropbear's 2222 is
#     disturbed and the two harnesses can be up at once
#   * its own ed25519 host key -- ed25519 is the ONLY host key algorithm
#     BebboSSH verifies, so an RSA-only server is unreachable from it
#   * its own authorized_keys holding one ed25519 key made here
#   * PasswordAuthentication no.  Not a policy choice: bebboscp says
#     "password login not supported" and public key is the only way in.
#   * Subsystem sftp.  bebboscp is an SFTP client, not an `scp -f`/`-t` client,
#     so a server with no sftp subsystem answers the channel request with a
#     failure and the transfer never starts.
#
# NO ROOT.  The login is the user running this script, whose key is the one
# authorised.
#
# THE CLIENT KEY IS MADE HERE, NOT ON THE AMIGA, AND THAT IS DELIBERATE.
#
#   BebboSSH's own ReadMe says its random generator is "rand() pimped with time
#   and vpos", and running bebbosshkeygen in the guest would additionally cost a
#   minute of ed25519 on a 14 MHz 68020 per run for a key nobody keeps.  So the
#   long-term key is generated by ssh-keygen here.  Its format is plain
#   unencrypted `openssh-key-v1`, which is exactly what src/loaded25519key.cpp
#   parses -- no format conversion is involved.
#
# KNOWN_HOSTS IS PRE-SEEDED, AND THAT IS NOT A SHORTCUT EITHER.
#
#   On an unknown host key BebboSSH prints "do you trust host ... ? Then enter:
#   yes" and reads stdin.  Under the runner stdin is NIL:, so the answer never
#   comes and the connection fails with a host-verify error that looks like a
#   handshake bug.  `knownhosts` prints the line it wants:
#
#       <host>[:<port>] ssh-ed25519 <base64 of SHA-256 of the host key blob>
#
#   which is OpenSSH's own SHA256 fingerprint, base64, with the '=' padding
#   BebboSSH's encoder emits and ssh-keygen's display omits.
#
# SPDX-License-Identifier: MIT

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
DIR="$ROOT/build/bebbossh-test"
PORT="${AMINETXDUO_BEBBOSSH_PORT:-2223}"
SSHD="${AMINETXDUO_SSHD:-}"

if [ -z "$SSHD" ]; then
    for cand in /usr/sbin/sshd /usr/bin/sshd /usr/local/sbin/sshd; do
        [ -x "$cand" ] && { SSHD="$cand"; break; }
    done
fi

# The sftp subsystem is a separate binary and its path is not the same on two
# systems.  Located rather than guessed, because a wrong path here produces a
# client-side "channel request failed" and nothing at all in the server log.
SFTP="${AMINETXDUO_SFTP_SERVER:-}"
if [ -z "$SFTP" ]; then
    for cand in /usr/libexec/sftp-server \
                /usr/lib/openssh/sftp-server \
                /usr/libexec/openssh/sftp-server \
                /usr/lib/ssh/sftp-server; do
        [ -x "$cand" ] && { SFTP="$cand"; break; }
    done
fi

action="${1:-status}"

# OpenSSH's SHA256:... display is the same base64 BebboSSH stores, minus the
# padding its encoder writes.  32 bytes always leaves one '='.
host_fingerprint() {
    ssh-keygen -lf "$DIR/hostkey_ed25519.pub" \
        | awk '{print $2}' | sed 's/^SHA256://; s/$/=/'
}

case "$action" in
start)
    [ -n "$SSHD" ] && [ -x "$SSHD" ] || {
        echo "no sshd found; set AMINETXDUO_SSHD=<path>" >&2; exit 2; }
    [ -n "$SFTP" ] || {
        echo "no sftp-server found; set AMINETXDUO_SFTP_SERVER=<path>" >&2
        echo "bebboscp is an SFTP client and cannot transfer without one." >&2
        exit 2; }

    mkdir -p "$DIR/xfer"

    if [ ! -f "$DIR/hostkey_ed25519" ]; then
        echo "==> host key (ed25519 -- the only kind BebboSSH verifies)"
        ssh-keygen -t ed25519 -f "$DIR/hostkey_ed25519" -N "" -q -C bebbossh-test
    fi

    if [ ! -f "$DIR/id_ed25519" ]; then
        echo "==> client key (OpenSSH format, made on the HOST -- see above)"
        ssh-keygen -t ed25519 -f "$DIR/id_ed25519" -N "" -q -C amiga
        cp "$DIR/id_ed25519.pub" "$DIR/authorized_keys"
        chmod 600 "$DIR/authorized_keys" "$DIR/id_ed25519"
    fi

    cat > "$DIR/sshd_config" <<EOF
Port $PORT
ListenAddress 0.0.0.0
HostKey $DIR/hostkey_ed25519
PidFile $DIR/sshd.pid
AuthorizedKeysFile $DIR/authorized_keys
PasswordAuthentication no
PubkeyAuthentication yes
KbdInteractiveAuthentication no
UsePAM no
StrictModes no
LogLevel VERBOSE
Subsystem sftp $SFTP
#
# LoginGraceTime is why this file exists rather than "just use the system
# sshd".  OpenSSH allows 120 seconds from TCP connect to completed
# authentication; BebboSSH's own ReadMe budgets about a minute for the
# connection on an unaccelerated machine and measures 0.9 s per X25519 key
# pair on an A3000.  A stock server WILL hang up on a 14 MHz 68020 -- which is
# a property of the machine, not a bug in either end, and the same shape as the
# Cloudflare TLS timeouts in docs/RESEARCH.md 11.8.  Raised here so a run
# measures the Amiga rather than the server's patience.
LoginGraceTime 900
EOF

    if [ -f "$DIR/sshd.pid" ] && kill -0 "$(cat "$DIR/sshd.pid")" 2>/dev/null; then
        echo "==> already running, pid $(cat "$DIR/sshd.pid")"
    else
        "$SSHD" -f "$DIR/sshd_config" -E "$DIR/sshd.log" -o LogLevel=DEBUG2
        sleep 1
    fi

    echo "==> sshd on port $PORT, pid $(cat "$DIR/sshd.pid" 2>/dev/null || echo '?')"
    echo "    user       : $(id -un)"
    echo "    client key : $DIR/id_ed25519"
    echo "    sftp       : $SFTP"
    echo "    log        : $DIR/sshd.log"
    ;;

stop)
    if [ -f "$DIR/sshd.pid" ]; then
        kill "$(cat "$DIR/sshd.pid")" 2>/dev/null || true
        rm -f "$DIR/sshd.pid"
        echo "==> stopped"
    else
        echo "==> not running"
    fi
    ;;

status)
    if [ -f "$DIR/sshd.pid" ] && kill -0 "$(cat "$DIR/sshd.pid")" 2>/dev/null; then
        echo "running, pid $(cat "$DIR/sshd.pid"), port $PORT"
    else
        echo "not running"
        exit 1
    fi
    ;;

knownhosts)
    [ -f "$DIR/hostkey_ed25519.pub" ] || { echo "no host key yet; run start" >&2; exit 2; }
    host="${2:-10.0.2.2}"
    if [ "$PORT" = "22" ]; then
        printf '%s ssh-ed25519 %s\n' "$host" "$(host_fingerprint)"
    else
        printf '%s:%s ssh-ed25519 %s\n' "$host" "$PORT" "$(host_fingerprint)"
    fi
    ;;

*)
    echo "usage: $0 {start|stop|status|knownhosts [host]}" >&2
    exit 2
    ;;
esac
