#!/usr/bin/env bash
# Packet-trace the stack, through its own bpf_* LVOs.
# SPDX-License-Identifier: MIT

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
MODEL=A1200
TIMEOUT=420
CLOCK=""
BUILD="${AMINETXDUO_BUILD:-build/cm}"
TAG="trace"
BASE_PORT=7300
BYTES=1048576
SNAP=96
CAPTURE=1

while getopts "m:t:k:b:T:P:B:s:N" opt; do
    case "$opt" in
        m) MODEL="$OPTARG" ;;
        t) TIMEOUT="$OPTARG" ;;
        k) CLOCK="$OPTARG" ;;
        b) BUILD="$OPTARG" ;;
        T) TAG="$OPTARG" ;;
        P) BASE_PORT="$OPTARG" ;;
        B) BYTES="$OPTARG" ;;
        s) SNAP="$OPTARG" ;;
        N) CAPTURE=0 ;;
        *) echo "usage: $0 [-m model] [-k MHz] [-t secs] [-b build] [-T tag]" \
                "[-P baseport] [-B bytes] [-s snaplen] [-N]" >&2; exit 2 ;;
    esac
done

BSD="$ROOT/$BUILD/src/bsdsocket/bsdsocket.library"
SMOKE="$ROOT/$BUILD/src/tools/ToolsSmoke"
TRACE="$ROOT/$BUILD/src/tools/NetTrace"
ADDIF="$ROOT/$BUILD/src/tools/AddNetInterface"

for f in "$BSD" "$SMOKE" "$TRACE" "$ADDIF"; do
    [ -f "$f" ] || { echo "missing $f, build it first" >&2; exit 2; }
done

A2065="${AMINETXDUO_A2065:-}"
if [ -z "$A2065" ]; then
    for candidate in \
        "$ROOT/build/a2065.device" \
        "$HOME/amiga-os-src/os-source/other_networking/sana2/bin/devs/a2065.device"
    do
        [ -f "$candidate" ] && { A2065="$candidate"; break; }
    done
fi
[ -n "$A2065" ] && [ -f "$A2065" ] || {
    echo "No a2065.device found. Set AMINETXDUO_A2065=<path>." >&2; exit 2; }

STAGE="$ROOT/build/trace-stage-$TAG"
rm -rf "$STAGE"
mkdir -p "$STAGE/libs"
cp -R "$ROOT/tests/netstack/devs" "$STAGE/devs"
cp "$A2065" "$STAGE/devs/a2065.device"
cp "$BSD"   "$STAGE/libs/bsdsocket.library"
cp "$TRACE" "$STAGE/NetTrace"
cp "$ADDIF" "$STAGE/AddNetInterface"

CAPARG=""
[ "$CAPTURE" = "1" ] || CAPARG=" NOCAPTURE"

{
    echo "# generated by tests/trace/run-trace.sh"
    echo "SYS:NetTrace LOOPBACK BYTES=$BYTES OUT=DH0:lo-warm.pcap SNAP=$SNAP NOCAPTURE"
    echo "SYS:NetTrace LOOPBACK BYTES=$BYTES OUT=DH0:lo.pcap SNAP=$SNAP$CAPARG"
    echo "SYS:AddNetInterface eth0"
    echo "SYS:NetTrace WIRE HOST=10.0.2.2 PORT=$BASE_PORT PATH=/bytes/$BYTES OUT=DH0:wire-warm.pcap SNAP=$SNAP NOCAPTURE"
    echo "SYS:NetTrace WIRE HOST=10.0.2.2 PORT=$BASE_PORT PATH=/bytes/$BYTES OUT=DH0:wire.pcap SNAP=$SNAP$CAPARG"
} > "$STAGE/commands.txt"

PEERLOG="$ROOT/build/tracepeer-$TAG.log"
python3 "$ROOT/tests/peer/httppeer.py" --base-port "$BASE_PORT" \
        --log "$PEERLOG" --seconds "$((TIMEOUT + 120))" \
        > "$ROOT/build/tracepeer-$TAG.out" 2>&1 &
PEER_PID=$!
trap 'kill "$PEER_PID" 2>/dev/null || true' EXIT
sleep 2
kill -0 "$PEER_PID" 2>/dev/null || {
    echo "httppeer.py did not start:" >&2
    cat "$ROOT/build/tracepeer-$TAG.out" >&2
    exit 2
}

export AMINETXDUO_RUN_TAG="$TAG"

CPUARG=()
[ -z "$CLOCK" ] || CPUARG+=(-k "$CLOCK")

echo "==> stack: $BUILD   model: $MODEL${CLOCK:+ at ${CLOCK} MHz}"
echo "==> peer on 127.0.0.1:$BASE_PORT, guest reaches it as 10.0.2.2"
echo "==> $BYTES bytes per workload, snaplen $SNAP, capture=$CAPTURE"

set +e
"$ROOT/tools/emu-net-run.sh" -n -m "$MODEL" -t "$TIMEOUT" "${CPUARG[@]}" \
    "$SMOKE" "$STAGE/devs" "$STAGE/libs" "$STAGE/NetTrace" \
    "$STAGE/AddNetInterface" "$STAGE/commands.txt" \
    > "$ROOT/build/trace-$TAG.log" 2>&1
RC=$?
set -e

HD="$ROOT/build/testhd-$TAG"

echo
echo "================ what the Amiga said ================"
[ -f "$HD/tools.txt" ] && cat "$HD/tools.txt" || echo "(no tools.txt)"

echo
echo "================ analysis ================"
for f in "$HD"/lo.pcap "$HD"/wire.pcap; do
    [ -s "$f" ] || continue
    echo
    python3 "$ROOT/tests/trace/tcpaudit.py" "$f" || true
done

echo
echo "emulator log:  build/trace-$TAG.log"
echo "serial log:    build/serial-$TAG.log"
echo "peer log:      $PEERLOG"
echo "guest files:   $HD"

exit "$RC"
