/*
 * AmiNetXDuo, crypto68k P-256 correctness.
 *
 * The gate for src/crypto68k/c68k_p256.c.  A subtly wrong point addition does
 * not produce garbage; it produces a different point on the same curve, which
 * passes every plausibility check anyone would think to write.  So nothing
 * here checks that a result "looks like" a point.  Everything is checked
 * against a value computed somewhere else:
 *
 *   1. The field layer on its own, against the vendored multiply-and-reduce.
 *      A reduction that is wrong only for a rare carry pattern shows up in a
 *      scalar multiplication as one bad trial in a thousand, and is very hard
 *      to localise from there.
 *
 *   2. Known answers.  Scalar multiplication against a table generated by
 *      Python's arbitrary precision arithmetic in affine coordinates, a
 *      different representation, a different algorithm, and no shared code.
 *
 *   3. Differential.  Several hundred random scalars through the unmodified
 *      vendored _nx_crypto_ec_fp_projective_multiple and through this module,
 *      compared limb for limb.  Both the fixed-base path (k*G) and the generic
 *      path (k*Q) are covered, with the boundary cases: k = 0, 1, 2, n-1, n,
 *      2^256-1, and the small scalars where the running accumulator becomes
 *      equal to a table entry and the addition formula degenerates into a
 *      doubling.
 *
 *   4. ECDSA verify, end to end, through the real _nx_crypto_ecdsa_verify with
 *      only the curve's point multiplication swapped, on RFC 6979 A.2.5
 *      signatures.
 *
 *   5. ECDSA verify rejecting eight invalid signatures.  An "optimisation"
 *      that made verify always return success would pass items 1 through 3
 *      unchanged.
 *
 *   6. ECDH shared secret, end to end, against a known answer and against the
 *      vendored implementation, computed from both sides so the answer is not
 *      a restatement of one multiplication.
 *
 * SPDX-License-Identifier: MIT
 */

#include "c68k_support.h"
#include "c68k_p256.h"
#include "aminetxduo/crashguard.h"

#include "nx_crypto_ec.h"
#include "nx_crypto_ecdh.h"
#include "nx_crypto_ecdsa.h"

#include <exec/types.h>
#include <proto/exec.h>

#include "c68k_ec_vectors.h"


static ULONG    t_checks;
static ULONG    t_failures;

static NX_CRYPTO_EC     *t_ref_curve;
static NX_CRYPTO_EC      t_opt_curve;

/* Scratch for the vendored routines.  Generous and static: the AmigaOS process
   stack this runs on is 4 KB. */
static HN_UBASE     t_scratch_a[2048];
static HN_UBASE     t_scratch_b[2048];
static HN_UBASE     t_store[512];

static NX_CRYPTO_ECDH   t_ecdh;


static VOID t_check(UINT ok, const char *what)
{

    t_checks++;

    if (!ok)
    {
        t_failures++;
        c68k_log("  FAIL: %s", (LONG)what);
    }
}


/* ------------------------------------------------------------- helpers --- */

static HN_UBASE *t_alloc_point(NX_CRYPTO_EC_POINT *p, HN_UBASE *sp)
{

    NX_CRYPTO_EC_POINT_INITIALIZE(p, NX_CRYPTO_EC_POINT_AFFINE, sp, 32);
    return(sp);
}


static VOID t_set_scalar(NX_CRYPTO_HUGE_NUMBER *h, const HN_UBASE *limbs)
{

UINT    i;


    for (i = 0; i < 8u; i++)
    {
        h -> nx_crypto_huge_number_data[i] = limbs[i];
    }
    h -> nx_crypto_huge_number_size = 8u;
    h -> nx_crypto_huge_number_is_negative = NX_CRYPTO_FALSE;
    _nx_crypto_huge_number_adjust_size(h);
}


static UINT t_hn_is(const NX_CRYPTO_HUGE_NUMBER *h, const HN_UBASE *limbs)
{

UINT        i;
HN_UBASE    v;


    for (i = 0; i < 8u; i++)
    {
        v = (i < h -> nx_crypto_huge_number_size) ?
            h -> nx_crypto_huge_number_data[i] : 0UL;
        if (v != limbs[i])
        {
            return(0u);
        }
    }

    return(1u);
}


static UINT t_points_equal(const NX_CRYPTO_EC_POINT *a,
                           const NX_CRYPTO_EC_POINT *b)
{

UINT        i;
HN_UBASE    va;
HN_UBASE    vb;


    for (i = 0; i < 8u; i++)
    {
        va = (i < a -> nx_crypto_ec_point_x.nx_crypto_huge_number_size) ?
             a -> nx_crypto_ec_point_x.nx_crypto_huge_number_data[i] : 0UL;
        vb = (i < b -> nx_crypto_ec_point_x.nx_crypto_huge_number_size) ?
             b -> nx_crypto_ec_point_x.nx_crypto_huge_number_data[i] : 0UL;
        if (va != vb)
        {
            return(0u);
        }

        va = (i < a -> nx_crypto_ec_point_y.nx_crypto_huge_number_size) ?
             a -> nx_crypto_ec_point_y.nx_crypto_huge_number_data[i] : 0UL;
        vb = (i < b -> nx_crypto_ec_point_y.nx_crypto_huge_number_size) ?
             b -> nx_crypto_ec_point_y.nx_crypto_huge_number_data[i] : 0UL;
        if (va != vb)
        {
            return(0u);
        }
    }

    return(1u);
}


/* --------------------------------------------------- 2. known answers ---- */

static VOID t_known_answers(VOID)
{

c68k_p256_aff           got;
static c68k_p256_work   work;
c68k_p256_aff           q;
UINT                    i;
UINT                    n;
UINT                    ok;


    c68k_log("");
    c68k_log("2. Scalar multiplication against Python-derived known answers:");

    for (i = 0; i < 8u; i++)
    {
        q.x[i] = v_q_fixed[i];
        q.y[i] = v_q_fixed[i + 8u];
    }

    n = (UINT)(sizeof(v_scalars) / sizeof(v_scalars[0]));

    for (i = 0; i < n; i++)
    {
        c68k_p256_mul_g(&got, v_scalars[i].k);
        ok = 1u;
        if ((c68k_cmp(got.x, v_scalars[i].gx, 8u) != 0) ||
            (c68k_cmp(got.y, v_scalars[i].gy, 8u) != 0))
        {
            ok = 0u;
        }
        t_check(ok, "k * G");

        c68k_p256_mul_point(&got, &q, v_scalars[i].k, &work);
        ok = 1u;
        if ((c68k_cmp(got.x, v_scalars[i].qx, 8u) != 0) ||
            (c68k_cmp(got.y, v_scalars[i].qy, 8u) != 0))
        {
            ok = 0u;
        }
        t_check(ok, "k * Q");
    }

    c68k_log("  %lu scalars, comb and wNAF paths both", (ULONG)n);
}


/* ---------------------------------------------------- 3. differential ---- */

/*
 * Every scalar goes through the vendored routine and through ours.  The
 * vendored one is the reference and is not touched, so a disagreement is
 * always ours.
 */
static VOID t_differential(ULONG trials)
{

NX_CRYPTO_EC_POINT      ref;
NX_CRYPTO_EC_POINT      opt;
NX_CRYPTO_EC_POINT      base;
NX_CRYPTO_HUGE_NUMBER   d;
HN_UBASE               *sp;
HN_UBASE                k[8];
ULONG                   t;
UINT                    i;
UINT                    generic;
UINT                    mismatched;


    c68k_log("");
    c68k_log("3. Differential against the unmodified vendored routine:");

    mismatched = 0;

    for (t = 0; t < trials; t++)
    {
        sp = t_store;
        sp = t_alloc_point(&ref, sp);
        sp = t_alloc_point(&opt, sp);
        sp = t_alloc_point(&base, sp);
        NX_CRYPTO_HUGE_NUMBER_INITIALIZE(&d, sp, 32);

        for (i = 0; i < 8u; i++)
        {
            k[i] = c68k_rand();
        }

        /*
         * The first handful are the cases a random scalar essentially never
         * reaches, and where a point routine goes wrong if it is going to:
         * zero, one, the order and its neighbours, and all ones.
         */
        switch ((UINT)t)
        {
        case 0:  for (i = 0; i < 8u; i++) { k[i] = 0; }                 break;
        case 1:  for (i = 0; i < 8u; i++) { k[i] = 0; } k[0] = 1UL;     break;
        case 2:  for (i = 0; i < 8u; i++) { k[i] = 0; } k[0] = 2UL;     break;
        case 3:  k[0] = 0xFC632550UL; k[1] = 0xF3B9CAC2UL;
                 k[2] = 0xA7179E84UL; k[3] = 0xBCE6FAADUL;
                 k[4] = 0xFFFFFFFFUL; k[5] = 0xFFFFFFFFUL;
                 k[6] = 0x00000000UL; k[7] = 0xFFFFFFFFUL;              break;
        case 4:  k[0] = 0xFC632551UL; k[1] = 0xF3B9CAC2UL;
                 k[2] = 0xA7179E84UL; k[3] = 0xBCE6FAADUL;
                 k[4] = 0xFFFFFFFFUL; k[5] = 0xFFFFFFFFUL;
                 k[6] = 0x00000000UL; k[7] = 0xFFFFFFFFUL;              break;
        case 5:  k[0] = 0xFC632552UL; k[1] = 0xF3B9CAC2UL;
                 k[2] = 0xA7179E84UL; k[3] = 0xBCE6FAADUL;
                 k[4] = 0xFFFFFFFFUL; k[5] = 0xFFFFFFFFUL;
                 k[6] = 0x00000000UL; k[7] = 0xFFFFFFFFUL;              break;
        case 6:  for (i = 0; i < 8u; i++) { k[i] = 0xFFFFFFFFUL; }      break;
        default:                                                        break;
        }

        /*
         * Trials 7..49 use small scalars: that is where the accumulator
         * repeatedly equals a table entry, the case the mixed-addition formula
         * cannot handle without an explicit test.  It is also cheap, and the
         * reference generic multiplication costs about five seconds on this
         * machine against a budget of a few minutes for the whole run.  The
         * full-width random scalars are trials 50 and up; the edge values
         * (0, 1, 2, n-1, n, n+1, all ones) are trials 0..6.
         */
        generic = (UINT)(t & 1u);

        if (generic == 0u)
        {
            if ((t >= 7UL) && (t < 50UL))
            {
                for (i = 0; i < 8u; i++)
                {
                    k[i] = 0;
                }
                k[0] = (HN_UBASE)(1UL + (t >> 1));
            }
            t_set_scalar(&d, k);
            _nx_crypto_ec_fp_projective_multiple(t_ref_curve,
                                                 &t_ref_curve -> nx_crypto_ec_g,
                                                 &d, &ref, t_scratch_a);
            c68k_p256_ec_multiple(&t_opt_curve, &t_opt_curve.nx_crypto_ec_g,
                                  &d, &opt, t_scratch_b);
        }
        else
        {
            /*
             * A generic point, and for the low trials a small scalar, so that
             * the accumulator repeatedly lands on a table entry, the
             * doubling-versus-addition boundary the mixed-addition formula
             * cannot handle without an explicit test.
             */
            NX_CRYPTO_HUGE_NUMBER  seed;

            NX_CRYPTO_HUGE_NUMBER_INITIALIZE(&seed, sp, 32);
            seed.nx_crypto_huge_number_data[0] = (HN_UBASE)(t + 3UL);
            seed.nx_crypto_huge_number_size = 1u;
            seed.nx_crypto_huge_number_is_negative = NX_CRYPTO_FALSE;
            _nx_crypto_ec_fp_projective_multiple(t_ref_curve,
                                                 &t_ref_curve -> nx_crypto_ec_g,
                                                 &seed, &base, t_scratch_a);

            if ((t >= 7UL) && (t < 50UL))
            {
                for (i = 0; i < 8u; i++)
                {
                    k[i] = 0;
                }
                k[0] = (HN_UBASE)(1UL + (t >> 1));
            }

            t_set_scalar(&d, k);
            _nx_crypto_ec_fp_projective_multiple(t_ref_curve, &base, &d, &ref,
                                                 t_scratch_a);
            c68k_p256_ec_multiple(&t_opt_curve, &base, &d, &opt, t_scratch_b);
        }

        if (!t_points_equal(&ref, &opt))
        {
            mismatched++;
            if (mismatched <= 3u)
            {
                c68k_log("  FAIL trial %lu (%s path), k[0]=%lx k[7]=%lx",
                         t, (LONG)(generic ? "generic" : "fixed"),
                         (ULONG)k[0], (ULONG)k[7]);
            }
        }
        t_check(t_points_equal(&ref, &opt), "differential scalar multiply");
    }

    c68k_log("  %lu scalars, %lu mismatches", trials, (ULONG)mismatched);
}


/* --------------------------------------------------- 4/5. ECDSA verify --- */

static VOID t_ecdsa(VOID)
{

static HN_UBASE     ecdsa_scratch[NX_CRYPTO_ECDSA_SCRATCH_BUFFER_SIZE >> HN_SIZE_SHIFT];
UINT                status;
UINT                i;
UINT                n;
UCHAR               tampered[64];


    c68k_log("");
    c68k_log("4. ECDSA verify, RFC 6979 A.2.5 signatures, through the real");
    c68k_log("   _nx_crypto_ecdsa_verify with only nx_crypto_ec_multiple swapped:");

    status = _nx_crypto_ecdsa_verify(&t_opt_curve, (UCHAR *)v_hash_sample, 32u,
                                     (UCHAR *)v_pubkey, 65u,
                                     (UCHAR *)v_sig_sample,
                                     (UINT)sizeof(v_sig_sample),
                                     ecdsa_scratch);
    t_check(status == NX_CRYPTO_SUCCESS, "verify RFC 6979 \"sample\"");

    status = _nx_crypto_ecdsa_verify(&t_opt_curve, (UCHAR *)v_hash_test, 32u,
                                     (UCHAR *)v_pubkey, 65u,
                                     (UCHAR *)v_sig_test,
                                     (UINT)sizeof(v_sig_test),
                                     ecdsa_scratch);
    t_check(status == NX_CRYPTO_SUCCESS, "verify RFC 6979 \"test\"");

    /* And the reference agrees, so the vectors are not the thing under test. */
    status = _nx_crypto_ecdsa_verify(t_ref_curve, (UCHAR *)v_hash_sample, 32u,
                                     (UCHAR *)v_pubkey, 65u,
                                     (UCHAR *)v_sig_sample,
                                     (UINT)sizeof(v_sig_sample),
                                     ecdsa_scratch);
    t_check(status == NX_CRYPTO_SUCCESS, "reference verifies the same signature");

    c68k_log("  2 published signatures accepted by both implementations");

    c68k_log("");
    c68k_log("5. ECDSA verify must REJECT bad signatures:");

    n = (UINT)(sizeof(v_bad_sigs) / sizeof(v_bad_sigs[0]));
    for (i = 0; i < n; i++)
    {
        status = _nx_crypto_ecdsa_verify(&t_opt_curve, (UCHAR *)v_hash_sample,
                                         32u, (UCHAR *)v_pubkey, 65u,
                                         (UCHAR *)v_bad_sigs[i].sig,
                                         v_bad_sigs[i].len, ecdsa_scratch);
        if (status == NX_CRYPTO_SUCCESS)
        {
            c68k_log("  FAIL: bad signature '%s' was ACCEPTED",
                     (LONG)v_bad_sigs[i].name);
        }
        t_check(status != NX_CRYPTO_SUCCESS, "bad signature rejected");
    }

    /* A good signature against the wrong message digest. */
    status = _nx_crypto_ecdsa_verify(&t_opt_curve, (UCHAR *)v_hash_test, 32u,
                                     (UCHAR *)v_pubkey, 65u,
                                     (UCHAR *)v_sig_sample,
                                     (UINT)sizeof(v_sig_sample),
                                     ecdsa_scratch);
    t_check(status != NX_CRYPTO_SUCCESS, "wrong digest rejected");

    /* A good signature against a public key with one bit flipped.  The point
       is then off the curve, so key validation should catch it; the check is
       that it is rejected either way. */
    for (i = 0; i < 64u; i++)
    {
        tampered[i] = v_pubkey[i + 1u];
    }
    tampered[63] ^= 0x01;
    {
        UCHAR badkey[65];
        badkey[0] = 0x04;
        for (i = 0; i < 64u; i++)
        {
            badkey[i + 1u] = tampered[i];
        }
        status = _nx_crypto_ecdsa_verify(&t_opt_curve, (UCHAR *)v_hash_sample,
                                         32u, badkey, 65u,
                                         (UCHAR *)v_sig_sample,
                                         (UINT)sizeof(v_sig_sample),
                                         ecdsa_scratch);
        t_check(status != NX_CRYPTO_SUCCESS, "tampered public key rejected");
    }

    c68k_log("  %lu invalid inputs, all rejected as required", (ULONG)(n + 2u));
}


/* ------------------------------------------------------------- 6. ECDH --- */

static VOID t_ecdh_test(VOID)
{

UINT    status;
UCHAR   secret[32];
ULONG   secret_len;
UINT    i;
UINT    ok;


    c68k_log("");
    c68k_log("6. ECDH shared secret, end to end:");

    /*
     * _nx_crypto_ecdh_key_pair_import() sets the key size but not the curve
     * pointer, only _nx_crypto_ecdh_setup() does that, and setup generates a
     * random key, which a known-answer test cannot use.  So the curve is
     * assigned here.  Vendored behaviour, not ours; without it compute_secret
     * dereferences a null curve.
     */
    t_ecdh.nx_crypto_ecdh_curve = &t_opt_curve;
    status = _nx_crypto_ecdh_key_pair_import(&t_ecdh, &t_opt_curve,
                                             (UCHAR *)v_ecdh_priv, 32UL,
                                             (UCHAR *)v_ecdh_pub, 65UL);
    t_check(status == NX_CRYPTO_SUCCESS, "ECDH key pair import");

    secret_len = 0;
    status = _nx_crypto_ecdh_compute_secret(&t_ecdh, secret, 32UL, &secret_len,
                                            (UCHAR *)v_ecdh_peer, 65UL,
                                            t_ecdh.nx_crypto_ecdh_scratch_buffer);
    t_check(status == NX_CRYPTO_SUCCESS, "ECDH compute secret");
    t_check(secret_len == 32UL, "ECDH secret length");

    ok = 1u;
    for (i = 0; i < 32u; i++)
    {
        if (secret[i] != v_ecdh_secret[i])
        {
            ok = 0u;
        }
    }
    t_check(ok, "ECDH secret matches the known answer");

    /* The same computation through the vendored curve, for the differential. */
    t_ecdh.nx_crypto_ecdh_curve = t_ref_curve;
    status = _nx_crypto_ecdh_key_pair_import(&t_ecdh, t_ref_curve,
                                             (UCHAR *)v_ecdh_priv, 32UL,
                                             (UCHAR *)v_ecdh_pub, 65UL);
    t_check(status == NX_CRYPTO_SUCCESS, "ECDH import, reference curve");

    for (i = 0; i < 32u; i++)
    {
        secret[i] = 0;
    }
    status = _nx_crypto_ecdh_compute_secret(&t_ecdh, secret, 32UL, &secret_len,
                                            (UCHAR *)v_ecdh_peer, 65UL,
                                            t_ecdh.nx_crypto_ecdh_scratch_buffer);
    ok = (status == NX_CRYPTO_SUCCESS) ? 1u : 0u;
    for (i = 0; i < 32u; i++)
    {
        if (secret[i] != v_ecdh_secret[i])
        {
            ok = 0u;
        }
    }
    t_check(ok, "reference ECDH agrees with the same known answer");
}


/* ---------------------------------------------------- 1. field layer ----- */

static VOID t_field(VOID)
{

NX_CRYPTO_HUGE_NUMBER   a_hn;
NX_CRYPTO_HUGE_NUMBER   b_hn;
NX_CRYPTO_HUGE_NUMBER   r_hn;
HN_UBASE               *sp;
c68k_limb               a[8];
c68k_limb               b[8];
c68k_limb               r[8];
c68k_limb               prod[16];
ULONG                   t;
UINT                    i;
UINT                    ok;
ULONG                   bad;


    c68k_log("");
    c68k_log("1. Field arithmetic against the vendored multiply plus reduce:");

    bad = 0;

    for (t = 0; t < 400UL; t++)
    {
        sp = t_store;
        NX_CRYPTO_HUGE_NUMBER_INITIALIZE(&a_hn, sp, 32);
        NX_CRYPTO_HUGE_NUMBER_INITIALIZE(&b_hn, sp, 32);
        NX_CRYPTO_HUGE_NUMBER_INITIALIZE(&r_hn, sp, 96);

        for (i = 0; i < 8u; i++)
        {
            a[i] = c68k_rand();
            b[i] = c68k_rand();
        }

        /* Values at the top of the range exercise the reduction's carries. */
        if (t < 8UL)
        {
            for (i = 0; i < 8u; i++)
            {
                a[i] = 0xFFFFFFFFUL;
                b[i] = 0xFFFFFFFFUL;
            }
            a[7] = (t & 1UL) ? 0xFFFFFFFEUL : 0xFFFFFFFFUL;
        }

        /* Both operands must be below p for the vendored path to agree. */
        a[7] &= 0xFFFFFFFEUL;
        b[7] &= 0xFFFFFFFEUL;

        for (i = 0; i < 8u; i++)
        {
            a_hn.nx_crypto_huge_number_data[i] = a[i];
            b_hn.nx_crypto_huge_number_data[i] = b[i];
        }
        a_hn.nx_crypto_huge_number_size = 8u;
        b_hn.nx_crypto_huge_number_size = 8u;
        _nx_crypto_huge_number_adjust_size(&a_hn);
        _nx_crypto_huge_number_adjust_size(&b_hn);

        /* multiply */
        _nx_crypto_huge_number_multiply(&a_hn, &b_hn, &r_hn);
        t_ref_curve -> nx_crypto_ec_reduce(t_ref_curve, &r_hn, t_scratch_a);
        c68k_p256_fe_mul(r, a, b);
        ok = t_hn_is(&r_hn, r);
        if (!ok)
        {
            bad++;
        }
        t_check(ok, "fe_mul");

        /* square */
        _nx_crypto_huge_number_square(&a_hn, &r_hn);
        t_ref_curve -> nx_crypto_ec_reduce(t_ref_curve, &r_hn, t_scratch_a);
        c68k_p256_fe_sqr(r, a);
        ok = t_hn_is(&r_hn, r);
        if (!ok)
        {
            bad++;
        }
        t_check(ok, "fe_sqr");

        /* the reduction on its own, over a full 512-bit input */
        for (i = 0; i < 16u; i++)
        {
            prod[i] = c68k_rand();
            r_hn.nx_crypto_huge_number_data[i] = prod[i];
        }
        r_hn.nx_crypto_huge_number_size = 16u;
        r_hn.nx_crypto_huge_number_is_negative = NX_CRYPTO_FALSE;
        _nx_crypto_huge_number_adjust_size(&r_hn);
        t_ref_curve -> nx_crypto_ec_reduce(t_ref_curve, &r_hn, t_scratch_a);
        c68k_p256_fe_reduce(r, prod);
        ok = t_hn_is(&r_hn, r);
        if (!ok)
        {
            bad++;
        }
        t_check(ok, "fe_reduce");

        /* inverse: a * a^-1 must be 1 */
        c68k_p256_fe_inv(r, a);
        c68k_p256_fe_mul(r, r, a);
        ok = (r[0] == 1UL) ? 1u : 0u;
        for (i = 1; i < 8u; i++)
        {
            if (r[i] != 0)
            {
                ok = 0u;
            }
        }
        if (!ok)
        {
            bad++;
        }
        t_check(ok, "fe_inv");
    }

    c68k_log("  1600 field operations, %lu disagreements", bad);
}


/* ------------------------------------------------------------------ main -- */

int main(VOID)
{

UINT    status;


    ami_crash_set_reference((APTR)main, "crypto68k_ec_test");
    if (!ami_crash_install())
    {
        c68k_log("CRASHED -- see the serial log and DH0:crash.txt");
        c68k_flush();
        ami_crash_remove();
        return(20);
    }

    c68k_log("AmiNetXDuo -- crypto68k P-256 correctness");
    c68k_log("  limb primitives: %s",
             (LONG)(c68k_using_assembly() ? "68020 assembly" : "portable C"));

    c68k_rng_seed(0x0EC0DE01UL);

    t_ref_curve = NX_CRYPTO_NULL;
    status = _nx_crypto_ec_get_named_curve(&t_ref_curve, NX_CRYPTO_EC_SECP256R1);
    if ((status != NX_CRYPTO_SUCCESS) || (t_ref_curve == NX_CRYPTO_NULL))
    {
        c68k_log("FATAL: secp256r1 not available");
        c68k_flush();
        ami_crash_remove();
        return(20);
    }

    /*
     * The whole integration, in one statement: a copy of the curve with a
     * different point multiplication.  Everything above it, ECDSA, ECDH,
     * is the vendored code, unmodified, reached through the vendored API.
     */
    t_opt_curve = *t_ref_curve;
    t_opt_curve.nx_crypto_ec_multiple = c68k_p256_ec_multiple;

    t_check(c68k_p256_self_check() == NX_CRYPTO_SUCCESS,
            "comb table belongs to this curve");

    t_field();
    t_known_answers();
    t_differential(70UL);
    t_ecdsa();
    t_ecdh_test();

    c68k_log("");
    if (t_failures == 0)
    {
        c68k_log("%lu checks, 0 failures", t_checks);
    }
    else
    {
        c68k_log("%lu checks, %lu FAILURES", t_checks, t_failures);
    }

    c68k_flush();
    ami_crash_remove();

    return((t_failures == 0) ? 0 : 20);
}
