#!/usr/bin/env python3
"""Generate tests/crypto68k/c68k_ec_vectors.h.

    python3 tests/crypto68k/gen_ec_vectors.py > tests/crypto68k/c68k_ec_vectors.h

Two kinds of vector, and the distinction matters:

  PUBLISHED.  The ECDSA signatures are RFC 6979 A.2.5 (NIST P-256 with
  SHA-256, messages "sample" and "test"), values that exist outside this
  repository and were not produced by anything being tested.  They are
  re-verified here by this script's own arithmetic before being emitted, so a
  transcription error cannot slip through as a passing test.

  DERIVED.  The scalar multiplication known answers and the ECDH shared secret
  are computed here, by a straightforward affine implementation using Python's
  arbitrary precision integers and pow(x, -1, p) for inversion.  It shares no
  code, no representation and no algorithm with what it checks: the C is
  Jacobian with a Solinas reduction and a comb, this is affine with a modular
  inverse per addition.

The negative signatures exist because an "optimisation" that makes verify
always succeed passes every positive test there is.

SPDX-License-Identifier: MIT
"""

import hashlib
import sys

P = (1 << 256) - (1 << 224) + (1 << 192) + (1 << 96) - 1
A = P - 3
B = 0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B
N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
G = (0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296,
     0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5)


def add(p, q):
    if p is None:
        return q
    if q is None:
        return p
    x1, y1 = p
    x2, y2 = q
    if x1 == x2:
        if (y1 + y2) % P == 0:
            return None
        lam = (3 * x1 * x1 + A) * pow(2 * y1, P - 2, P) % P
    else:
        lam = (y2 - y1) * pow(x2 - x1, P - 2, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)


def mul(k, p):
    r = None
    while k:
        if k & 1:
            r = add(r, p)
        p = add(p, p)
        k >>= 1
    return r


def verify(pub, digest, r, s):
    if not (1 <= r < N and 1 <= s < N):
        return False
    z = int.from_bytes(digest, "big")
    w = pow(s, N - 2, N)
    pt = add(mul(z * w % N, G), mul(r * w % N, pub))
    return pt is not None and pt[0] % N == r


def der_int(v):
    b = v.to_bytes((v.bit_length() + 7) // 8 or 1, "big")
    if b[0] & 0x80:
        b = b"\x00" + b
    return bytes([0x02, len(b)]) + b


def der_sig(r, s):
    body = der_int(r) + der_int(s)
    return bytes([0x30, len(body)]) + body


def emit_bytes(name, data):
    out = sys.stdout.write
    out("static const UCHAR %s[%u] =\n{\n" % (name, len(data)))
    for i in range(0, len(data), 12):
        out("    " + " ".join("0x%02X," % b for b in data[i:i + 12]) + "\n")
    out("};\n\n")


def emit_limbs(name, v):
    out = sys.stdout.write
    limbs = [(v >> (32 * i)) & 0xFFFFFFFF for i in range(8)]
    out("static const HN_UBASE %s[8] =\n{\n" % name)
    for i in range(0, 8, 4):
        out("    " + " ".join("0x%08XUL," % x for x in limbs[i:i + 4]) + "\n")
    out("};\n\n")


def main():
    out = sys.stdout.write

    priv = 0xC9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721
    pub = mul(priv, G)
    assert pub == (0x60FED4BA255A9D31C961EB74C6356D68C049B8923B61FA6CE669622E60F29FB6,
                   0x7903FE1008B8BC99A41AE9E95628BC64F2F1B20C2D7E9F5177A3C294D4462299), \
        "RFC 6979 A.2.5 public key does not match -- the curve arithmetic here is wrong"

    sample = (b"sample",
              0xEFD48B2AACB6A8FD1140DD9CD45E81D69D2C877B56AAF991C34D0EA84EAF3716,
              0xF7CB1C942D657C41D436C7A1B6E29F65F3E900DBB9AFF4064DC4AB2F843ACDA8)
    test = (b"test",
            0xF1ABB023518351CD71D881567B1EA663ED3EFCF6C5132B354F28D3B0B7D38367,
            0x019F4113742A2B14BD25926B49C649155F267E60D3814B4C0CC84250E46F0083)

    for msg, r, s in (sample, test):
        digest = hashlib.sha256(msg).digest()
        assert verify(pub, digest, r, s), \
            "RFC 6979 vector for %r does not verify -- transcription error" % msg

    # ECDH: two key pairs, shared secret both ways so the answer is not a
    # restatement of one multiplication.
    d_a = 0x7D7DC5F71EB29DDAF80D6214632EEAE03D9058AF1FB6D22ED80BADB62BC1A534
    d_b = 0x38F65D6DCE47676044D58CE5139582D568F64BB16098D179DBAB07741DD5CAF5
    q_a = mul(d_a, G)
    q_b = mul(d_b, G)
    shared = mul(d_a, q_b)
    assert shared == mul(d_b, q_a)

    out("/*\n")
    out(" * AmiNetXDuo -- P-256 test vectors for tests/crypto68k.\n")
    out(" *\n")
    out(" * Generated by tests/crypto68k/gen_ec_vectors.py; do not edit.\n")
    out(" *\n")
    out(" * The ECDSA signatures are RFC 6979 A.2.5, NIST P-256 with SHA-256, for the\n")
    out(" * messages \"sample\" and \"test\".  Published values, not values this project\n")
    out(" * produced, and re-verified by the generator before emission.\n")
    out(" *\n")
    out(" * Everything else is derived by the generator's own affine arithmetic, which\n")
    out(" * shares no code with what it checks.\n")
    out(" *\n")
    out(" * SPDX-License-Identifier: MIT\n")
    out(" */\n\n")
    out("#ifndef AMINETXDUO_C68K_EC_VECTORS_H\n")
    out("#define AMINETXDUO_C68K_EC_VECTORS_H\n\n")
    out('#include "nx_crypto_huge_number.h"\n\n')

    emit_bytes("v_pubkey", b"\x04" + pub[0].to_bytes(32, "big") +
                           pub[1].to_bytes(32, "big"))

    for label, (msg, r, s) in (("sample", sample), ("test", test)):
        emit_bytes("v_hash_" + label, hashlib.sha256(msg).digest())
        emit_bytes("v_sig_" + label, der_sig(r, s))

    # Negative cases.  Each must be REJECTED; a verify that always succeeds is
    # the failure mode this whole file exists to catch.
    msg, r, s = sample
    digest = hashlib.sha256(msg).digest()
    bad = [
        ("r_plus_one", der_sig(r + 1, s)),
        ("s_plus_one", der_sig(r, s + 1)),
        ("r_zero", der_sig(0, s)),
        ("s_zero", der_sig(r, 0)),
        ("r_is_n", der_sig(N, s)),
        ("s_is_n", der_sig(N, s)),
        ("swapped", der_sig(s, r)),
        ("other_sig", der_sig(test[1], test[2])),
    ]
    for label, sig in bad:
        # Prove they really are invalid before shipping them as negatives.
        body = sig[2:]
        rl = body[1]
        rv = int.from_bytes(body[2:2 + rl], "big")
        sv = int.from_bytes(body[2 + rl + 2:], "big")
        assert not verify(pub, digest, rv, sv), \
            "negative vector %s actually verifies" % label

    out("typedef struct\n{\n    const UCHAR *sig;\n    UINT         len;\n"
        "    const char  *name;\n} V_BAD_SIG;\n\n")
    for label, sig in bad:
        emit_bytes("v_bad_" + label, sig)
    out("static const V_BAD_SIG v_bad_sigs[] =\n{\n")
    for label, sig in bad:
        out('    { v_bad_%s, %u, "%s" },\n' % (label, len(sig), label))
    out("};\n\n")

    emit_bytes("v_ecdh_priv", d_a.to_bytes(32, "big"))
    emit_bytes("v_ecdh_pub", b"\x04" + q_a[0].to_bytes(32, "big") +
                             q_a[1].to_bytes(32, "big"))
    emit_bytes("v_ecdh_peer", b"\x04" + q_b[0].to_bytes(32, "big") +
                              q_b[1].to_bytes(32, "big"))
    emit_bytes("v_ecdh_secret", shared[0].to_bytes(32, "big"))

    # Scalar multiplication known answers: k, k*G and k*Q for a fixed Q.
    q_fixed = mul(0x1234567890ABCDEF, G)
    scalars = [1, 2, 3, 4, 5, 7, 15, 16, 17, 31, 32, 33,
               (1 << 26), (1 << 52), (1 << 128), (1 << 255),
               N - 1, N - 2,
               0x6C1AF5AC1AE0E5B95FA6E0DDEBB6B29A0DDD8A6A2B4A0B3E0A5C7F9D2E1B3C4D,
               0x0000000000000000000000000000000000000000000000000000000000000101]
    out("typedef struct\n{\n    HN_UBASE k[8];\n    HN_UBASE gx[8];\n"
        "    HN_UBASE gy[8];\n    HN_UBASE qx[8];\n    HN_UBASE qy[8];\n"
        "} V_SCALAR;\n\n")
    out("static const HN_UBASE v_q_fixed[16] =\n{\n")
    vals = ([(q_fixed[0] >> (32 * i)) & 0xFFFFFFFF for i in range(8)] +
            [(q_fixed[1] >> (32 * i)) & 0xFFFFFFFF for i in range(8)])
    for i in range(0, 16, 4):
        out("    " + " ".join("0x%08XUL," % x for x in vals[i:i + 4]) + "\n")
    out("};\n\n")

    out("static const V_SCALAR v_scalars[] =\n{\n")
    for k in scalars:
        kg = mul(k, G)
        kq = mul(k, q_fixed)
        kg = (0, 0) if kg is None else kg
        kq = (0, 0) if kq is None else kq
        out("    {\n")
        for v in (k, kg[0], kg[1], kq[0], kq[1]):
            limbs = [(v >> (32 * i)) & 0xFFFFFFFF for i in range(8)]
            out("        { " + " ".join("0x%08XUL," % x for x in limbs) + " },\n")
        out("    },\n")
    out("};\n\n")

    out("#endif /* AMINETXDUO_C68K_EC_VECTORS_H */\n")


if __name__ == "__main__":
    main()
