/*
 * AmiNetXDuo, crypto68k: P-256 elliptic curve arithmetic for the 68020.
 *
 * Not constant time.  wNAF digits and comb digits select table entries by
 * value, and every conditional field correction is a branch.  Acceptable for
 * the threat model in docs/RESEARCH.md, not against a remote timing attacker.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef AMINETXDUO_C68K_P256_H
#define AMINETXDUO_C68K_P256_H

#include "crypto68k.h"
#include "nx_crypto_ec.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * A field element: eight limbs, least significant first, value in [0, p).
 * Fixed size, the variable size field of NX_CRYPTO_HUGE_NUMBER is a large
 * part of what this module avoids.
 */
#define C68K_P256_LIMBS     8u

typedef c68k_limb c68k_p256_fe[C68K_P256_LIMBS];

/* A point in Jacobian coordinates: (X : Y : Z) is affine (X/Z^2, Y/Z^3).
   Z == 0 is the point at infinity, and is the only representation of it. */
typedef struct
{
    c68k_p256_fe    x;
    c68k_p256_fe    y;
    c68k_p256_fe    z;
} c68k_p256_jac;

/* An affine point.  infinity is (0, 0), matching what the vendored
   _nx_crypto_ec_point_is_infinite() recognises. */
typedef struct
{
    c68k_p256_fe    x;
    c68k_p256_fe    y;
} c68k_p256_aff;


/*
 * Working memory for a generic scalar multiplication.  A parameter and not a
 * local because this runs under a 4 KB AmigaOS process stack, and not a
 * static because nx_crypto is otherwise reentrant.
 *
 *   naf   width-5 wNAF digits, at most 257 of them
 *   tab   q, 3q, 5q, ... 15q, Jacobian during the build, then converted in
 *         place to affine, after which the z field is dead
 *   acc   the running products a batch inversion needs
 */
#define C68K_P256_WNAF_W        5u
#define C68K_P256_WNAF_POINTS   (1u << (C68K_P256_WNAF_W - 2u))     /* 8 */

typedef struct
{
    signed char     naf[260];
    c68k_p256_jac   tab[C68K_P256_WNAF_POINTS];
    c68k_p256_fe    acc[C68K_P256_WNAF_POINTS];
} c68k_p256_work;

/* Scratch a caller must have spare, in HN_UBASE limbs, for the drop-in below. */
#define C68K_P256_WORK_LIMBS    ((sizeof(c68k_p256_work) + 3u) >> 2)


/* --------------------------------------------------------- comb table ---- */

/* Lim-Lee comb parameters.  Kept here rather than in the generated file so
   that a table built with different parameters fails to compile. */
#define C68K_P256_COMB_W        5u
#define C68K_P256_COMB_D        52u     /* ceil(256 / w) */
#define C68K_P256_COMB_E        26u     /* ceil(d / 2), the loop count */
#define C68K_P256_COMB_HALF     ((1u << C68K_P256_COMB_W) - 1u)     /* 31 */
#define C68K_P256_COMB_POINTS   (2u * C68K_P256_COMB_HALF)          /* 62 */

/* [0 .. 30] are T1[digit-1].  [31 .. 61] are T2[digit-1] = 2^e * T1[digit-1].
   Each row is x limbs 0..7 then y limbs 0..7.  Generated by
   src/crypto68k/gen_p256_table.py. */
extern const c68k_limb c68k_p256_comb[C68K_P256_COMB_POINTS][16];


/* -------------------------------------------------- carry primitives ----- */

/*
 * The three routines c68k_p256.S hand-writes, with portable C fallbacks in
 * c68k_p256.c under the same build flag as c68k_prim.S.  Exposed rather than
 * static because the assembly has to define them, and because the test drives
 * the reduction directly against the vendored one.
 *
 * GCC cannot generate the ADD.L / ADDX.L pair these need, C has no carry
 * flag, and the disassembly of both plausible C spellings is in the header
 * comment of c68k_p256.S.  The only place in the module where hand-written
 * assembly wins.  The multiply is already at the MULU.L floor and is left to
 * the compiler.
 */

/* r = a + b over eight limbs, no modular reduction.  Returns the carry out. */
c68k_limb c68k_p256_add_raw(c68k_limb *r, const c68k_limb *a, const c68k_limb *b);

/* r = a - b over eight limbs, no modular reduction.  Returns the borrow out. */
c68k_limb c68k_p256_sub_raw(c68k_limb *r, const c68k_limb *a, const c68k_limb *b);

/*
 * One pass of the Solinas reduction: writes r[0..7] and returns the leftover
 * signed coefficient of 2^256, which c68k_p256_fe_reduce() folds in.
 */
INT c68k_p256_reduce_core(c68k_limb *r, const c68k_limb *t);


/* ------------------------------------------------------ field, exposed --- */

/*
 * Exposed so the test can drive them directly against the vendored
 * equivalents.  A field bug otherwise surfaces only as "the wrong point"
 * three thousand operations later.
 */

/* r = a * b mod p.  r can alias a or b. */
VOID c68k_p256_fe_mul(c68k_p256_fe r, const c68k_p256_fe a, const c68k_p256_fe b);

/* r = a * a mod p.  r can alias a. */
VOID c68k_p256_fe_sqr(c68k_p256_fe r, const c68k_p256_fe a);

/* r = a + b mod p, r = a - b mod p.  r can alias either operand. */

/*
 * r = t mod p, where t is a 16-limb product.  The Solinas reduction, and the
 * hottest routine in the module.
 */
VOID c68k_p256_fe_reduce(c68k_p256_fe r, const c68k_limb t[16]);

/* r = a^-1 mod p, by binary extended Euclid.  a == 0 yields 0. */
VOID c68k_p256_fe_inv(c68k_p256_fe r, const c68k_p256_fe a);


/* ------------------------------------------------------------- points ---- */

/* r = 2 * p1.  r can alias p1.  Infinity in, infinity out. */
VOID c68k_p256_jac_double(c68k_p256_jac *r, const c68k_p256_jac *p1);

/*
 * r = p1 + q, q affine.  r can alias p1.  Handles every degenerate case:
 * p1 infinite, q infinite, p1 == q (doubles), and p1 == -q (infinity).
 */
VOID c68k_p256_jac_add_affine(c68k_p256_jac *r, const c68k_p256_jac *p1,
                              const c68k_p256_aff *q);

/* Jacobian to affine.  Infinity becomes (0, 0). */


/* -------------------------------------------- scalar multiplication ------ */

/*
 * r = k * G, using the fixed-base comb.  k is eight limbs, least significant
 * first, and need not be reduced, k == 0 gives infinity.
 */
VOID c68k_p256_mul_g(c68k_p256_aff *r, const c68k_limb k[C68K_P256_LIMBS]);

/*
 * r = k * q for an arbitrary affine q, width-5 wNAF with a batch-inverted
 * affine table.  q must be on the curve.  q at infinity gives infinity.
 * work is scratch, see c68k_p256_work above.  It must not alias anything.
 */
VOID c68k_p256_mul_point(c68k_p256_aff *r, const c68k_p256_aff *q,
                         const c68k_limb k[C68K_P256_LIMBS],
                         c68k_p256_work *work);


/* --------------------------------------------------------- integration --- */

/*
 * Signature-compatible drop-in for the nx_crypto_ec_multiple of NX_CRYPTO_EC.
 * One line wires it in:
 *
 *     curve -> nx_crypto_ec_multiple = c68k_p256_ec_multiple;
 *
 * on the secp256r1 curve only, which makes ECDH key generation, ECDH shared
 * secret and both halves of ECDSA verify take this path with no other change
 * anywhere.  Anything it cannot handle falls through to
 * _nx_crypto_ec_fp_projective_multiple(), so the substitution is safe.  That
 * is a curve that is not secp256r1, or a scalar wider than 256 bits, which
 * _nx_crypto_ec_precomputation() does use.
 */
VOID c68k_p256_ec_multiple(NX_CRYPTO_EC *curve,
                           NX_CRYPTO_EC_POINT *g,
                           NX_CRYPTO_HUGE_NUMBER *d,
                           NX_CRYPTO_EC_POINT *r,
                           HN_UBASE *scratch);

/*
 * Recompute two comb table entries from G with the generic routine and compare.
 * Returns NX_CRYPTO_SUCCESS, or NX_CRYPTO_NOT_SUCCESSFUL if the generated table
 * does not belong to this curve.  Two generic scalar multiplications.  Call it
 * once at startup for the check.
 */
UINT c68k_p256_self_check(VOID);

/* Diagnostic-only return values used by run-lto-probe.sh.  Normal builds
   preserve the public success/not-successful contract above. */
#define C68K_P256_CHECK_GENERIC_X    0x201u
#define C68K_P256_CHECK_GENERIC_Y    0x202u
#define C68K_P256_CHECK_COMB_X       0x203u
#define C68K_P256_CHECK_COMB_Y       0x204u
#define C68K_P256_CHECK_FIELD_MUL    0x211u
#define C68K_P256_CHECK_FIELD_SQR    0x212u
#define C68K_P256_CHECK_FIELD_INV    0x213u

#ifdef __cplusplus
}
#endif

#endif /* AMINETXDUO_C68K_P256_H */
