#!/usr/bin/env python3
"""Generate c68k_p256_table.c, the fixed-base comb table for P-256's G.

    python3 src/crypto68k/gen_p256_table.py > src/crypto68k/c68k_p256_table.c

The table is a Lim-Lee comb with w = 5 and two halves:

    d = ceil(256 / w) = 52      bits per comb row
    e = ceil(d / 2)   = 26      columns actually iterated

Row t of the comb covers scalar bits [t*d, t*d + d - 1].  Column c contributes
the digit  sum_t bit(k, t*d + c) << t, so a digit selects the table entry

    T1[digit - 1] = sum_t bit_t * 2^(t*d) * G          digit in 1..31
    T2[digit - 1] = 2^e * T1[digit - 1]

and the scalar multiplication is 26 doublings with two additions each, versus
256 doublings for a generic point.  That ratio is the whole reason a fixed-base
table exists.

Points are stored affine, x then y, eight 32-bit limbs each least significant
first, which is the layout c68k_p256.c computes in, so the table is loaded
with a copy and never byte-swapped.

SPDX-License-Identifier: MIT
"""

import sys

P  = (1 << 256) - (1 << 224) + (1 << 192) + (1 << 96) - 1
A  = P - 3
B  = 0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B
GX = 0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296
GY = 0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5

W = 5
D = (256 + W - 1) // W          # 52
E = (D + 1) // 2                # 26


def add(p, q):
    if p is None:
        return q
    if q is None:
        return p
    x1, y1 = p
    x2, y2 = q
    if x1 == x2:
        if (y1 + y2) % P == 0:
            return None
        lam = (3 * x1 * x1 + A) * pow(2 * y1, P - 2, P) % P
    else:
        lam = (y2 - y1) * pow(x2 - x1, P - 2, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)


def mul(k, p):
    r = None
    while k:
        if k & 1:
            r = add(r, p)
        p = add(p, p)
        k >>= 1
    return r


def limbs(v):
    return [(v >> (32 * i)) & 0xFFFFFFFF for i in range(8)]


def main():
    g = (GX, GY)

    # Sanity: G must satisfy the curve equation, and n*G must be infinity.
    assert (GY * GY - GX * GX * GX - A * GX - B) % P == 0
    n = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
    assert mul(n, g) is None

    rows = [mul(1 << (t * D), g) for t in range(W)]

    t1 = []
    for digit in range(1, 1 << W):
        acc = None
        for t in range(W):
            if digit & (1 << t):
                acc = add(acc, rows[t])
        t1.append(acc)

    t2 = [mul(1 << E, pt) for pt in t1]

    out = sys.stdout.write
    out("/*\n")
    out(" * AmiNetXDuo, crypto68k: fixed-base comb table for P-256's base point.\n")
    out(" *\n")
    out(" * GENERATED by src/crypto68k/gen_p256_table.py, do not edit.\n")
    out(" *\n")
    out(" * Lim-Lee comb, w = %u, d = %u, e = %u.  Two halves of %u points each,\n"
        % (W, D, E, (1 << W) - 1))
    out(" * affine, x then y, eight 32-bit limbs least significant first.\n")
    out(" *\n")
    out(" * The table is checked at run time, not merely trusted: c68k_p256_self_check()\n")
    out(" * recomputes entry 1 of each half from G with the generic point routine and\n")
    out(" * compares.  A table generated for the wrong curve would otherwise produce\n")
    out(" * points that are perfectly valid and completely wrong.\n")
    out(" *\n")
    out(" * SPDX-License-Identifier: MIT\n")
    out(" */\n\n")
    out('#include "c68k_p256.h"\n\n')
    out("const c68k_limb c68k_p256_comb[C68K_P256_COMB_POINTS][16] =\n{\n")

    for half, table in (("T1", t1), ("T2", t2)):
        for i, pt in enumerate(table):
            x, y = pt
            vals = limbs(x) + limbs(y)
            digit = i + 1
            terms = " + ".join("2^%u" % (t * D)
                               for t in range(W) if digit & (1 << t))
            out("    /* %s digit %u = %s(%s) * G */\n"
                % (half, digit, "2^%u * " % E if half == "T2" else "", terms))
            out("    {\n")
            for row in range(4):
                out("        " + " ".join("0x%08XUL," % v
                                          for v in vals[row * 4:row * 4 + 4]) + "\n")
            out("    },\n")

    out("};\n")


if __name__ == "__main__":
    main()
