#!/bin/sh
#
# The published tables really are derivable from the raw ledger.
#
#   tools/aminet-survey/check-derived.sh
#
# docs/aminet-survey/README.md says lvo-usage.tsv and lvo-rare.tsv are derived
# from results.tsv plus lvomap.tsv.  That is a claim about the data, so it is
# checked here rather than believed: both are regenerated into a temporary file
# and compared byte for byte with what is committed.
#
# It catches the two ways the published set goes wrong -- a derived file
# updated while the ledger it came from was not, and a ledger updated while the
# derived files were left behind.  Either makes every number downstream a
# statement about a dataset that no longer exists.
#
# SPDX-License-Identifier: MIT

set -u
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT" || exit 2
D=docs/aminet-survey
T=$(mktemp -d) || exit 2
trap 'rm -rf "$T"' EXIT

for f in results.tsv lvomap.tsv lvo-usage.tsv lvo-rare.tsv vsyslog-callers.tsv \
         unused-vectors.tsv candidates.tsv; do
    [ -r "$D/$f" ] || { echo "check_derived=FAIL missing $D/$f"; exit 2; }
done

# THE DERIVATION LIVES IN ONE PLACE.  This gate used to carry its own copy of
# the counting rule, inline, and tick.sh carried another -- so it could only
# ever catch a stale file.  Change the rule in one copy and the gate cheerfully
# confirms that the wrong table is the right one.  Both now call usage.py.
python3 tools/aminet-survey/usage.py "$D" "$T/lvo-usage.tsv" \
    || { echo "check_derived=FAIL regenerating lvo-usage"; exit 2; }

if ! diff -q "$T/lvo-usage.tsv" "$D/lvo-usage.tsv" > /dev/null 2>&1; then
    echo "check_derived=FAIL lvo-usage.tsv does not match results.tsv"
    diff "$D/lvo-usage.tsv" "$T/lvo-usage.tsv" | head -8
    exit 1
fi

# lvo-rare.tsv, regenerated the same way and compared the same way.  Counting
# its rows -- which is all this did at first -- is not checking it: a stale
# lvo-rare.tsv has exactly the row count it always had.  A gate that reports on
# a file it did not regenerate is worse than one that says nothing about it.
python3 tools/aminet-survey/rare.py 10 "$D" "$T/lvo-rare.tsv" \
    || { echo "check_derived=FAIL regenerating lvo-rare"; exit 2; }

if ! diff -q "$T/lvo-rare.tsv" "$D/lvo-rare.tsv" > /dev/null 2>&1; then
    echo "check_derived=FAIL lvo-rare.tsv does not match results.tsv"
    diff "$D/lvo-rare.tsv" "$T/lvo-rare.tsv" | head -8
    exit 1
fi

# vsyslog-callers.tsv, the evidence handed to codex for the implementation it
# owns.  A caller list that drifts from the ledger is worse than none: it reads
# as a survey result and is a leftover.
python3 tools/aminet-survey/callers.py vsyslog "$D" "$T/vsyslog-callers.tsv" \
    || { echo "check_derived=FAIL regenerating vsyslog-callers"; exit 2; }

if ! diff -q "$T/vsyslog-callers.tsv" "$D/vsyslog-callers.tsv" > /dev/null 2>&1; then
    echo "check_derived=FAIL vsyslog-callers.tsv does not match results.tsv"
    diff "$D/vsyslog-callers.tsv" "$T/vsyslog-callers.tsv" | head -8
    exit 1
fi

# unused-vectors.tsv and candidates.tsv, both called derived by the README and
# both regenerated by nothing until now.  A file documented as derived and
# checked by no gate is exactly the state lvo-rare.tsv was in.
python3 tools/aminet-survey/unused.py "$D" "$T/unused-vectors.tsv" \
    || { echo "check_derived=FAIL regenerating unused-vectors"; exit 2; }
if ! diff -q "$T/unused-vectors.tsv" "$D/unused-vectors.tsv" > /dev/null 2>&1; then
    echo "check_derived=FAIL unused-vectors.tsv does not match lvo-usage.tsv"
    diff "$D/unused-vectors.tsv" "$T/unused-vectors.tsv" | head -8
    exit 1
fi

python3 tools/aminet-survey/candidates.py "$D" "$T/candidates.tsv" \
    || { echo "check_derived=FAIL regenerating candidates"; exit 2; }
if ! diff -q "$T/candidates.tsv" "$D/candidates.tsv" > /dev/null 2>&1; then
    echo "check_derived=FAIL candidates.tsv does not match results.tsv"
    diff "$D/candidates.tsv" "$T/candidates.tsv" | head -8
    exit 1
fi

rows=$(awk -F'\t' 'NR>1' "$D/lvo-usage.tsv" | wc -l)
called=$(awk -F'\t' 'NR>1 && $3>0' "$D/lvo-usage.tsv" | wc -l)
rare=$(awk -F'\t' 'NR>1 && !s[$2]++' "$D/lvo-rare.tsv" | wc -l)
echo "check_derived vectors=$rows called=$called rare_under_10=$rare"
vsys=$(wc -l < "$D/vsyslog-callers.tsv")
echo "check_derived vsyslog_callers=$vsys"
echo "check_derived regenerated=lvo-usage.tsv,lvo-rare.tsv,vsyslog-callers.tsv,\
unused-vectors.tsv,candidates.tsv"
echo "check_derived=PASS"
