#!/usr/bin/env python3
# AES-128-CCM known answers for test_ccm_contract.c, from an independent
# implementation: Python `cryptography` AESCCM (OpenSSL underneath).
#
#   python3 tests/ccm/gen_ccm_vectors.py > tests/ccm/ccm_vectors.h
#
# The plaintext and AAD are the patterns the test regenerates.  CTR output
# does not depend on the AAD or the tag length, and every plaintext is a
# prefix of the longest, so one 16384-byte ciphertext covers every case;
# the generator asserts that rather than assuming it.
#
# SPDX-License-Identifier: MIT
import sys
import cryptography
from cryptography.hazmat.primitives.ciphers.aead import AESCCM
from cryptography.hazmat.backends.openssl.backend import backend

KEY = bytes(range(0x40, 0x50))
NONCE = bytes(range(0x10, 0x1c))            # 12 bytes: L = 3, as TLS
PAYLOADS = [0, 1, 16, 4080, 4096, 4112, 16384]
SHORT_AADS = [0, 5, 13]
LONG_AADS = [65279, 65280, 70000]           # last 2-octet l(a), first 6-octet, beyond
LONG_PAYLOADS = [0, 16, 4096]
TAGS = [16, 8]
MAXLEN = max(PAYLOADS)

def pt(n):  return bytes(((i * 31) + 7) & 0xFF for i in range(n))
def aad(n): return bytes(((i * 13) + 101) & 0xFF for i in range(n))

cases = []
for p in PAYLOADS:
    for a in SHORT_AADS:
        for t in TAGS:
            cases.append((p, a, t))
for p in LONG_PAYLOADS:
    for a in LONG_AADS:
        for t in TAGS:
            cases.append((p, a, t))

full = AESCCM(KEY, tag_length=16).encrypt(NONCE, pt(MAXLEN), None)[:MAXLEN]
tags = []
for p, a, t in cases:
    out = AESCCM(KEY, tag_length=t).encrypt(NONCE, pt(p), aad(a) if a else None)
    assert out[:p] == full[:p]
    assert AESCCM(KEY, tag_length=t).decrypt(NONCE, out, aad(a) if a else None) == pt(p)
    tags.append(out[p:])

def arr(b, ind="    "):
    return "\n".join(ind + ", ".join("0x%02x" % x for x in b[i:i + 12]) + ","
                     for i in range(0, len(b), 12))

w = sys.stdout.write
w("/* Generated by tests/ccm/gen_ccm_vectors.py: Python %s, cryptography %s, %s.\n"
  "   Do not edit. */\n\n" % (sys.version.split()[0], cryptography.__version__,
                              backend.openssl_version_text()))
w("#define CCM_VEC_MAXLEN %d\n\n" % MAXLEN)
w("static const unsigned char ccm_vec_key[16] = {\n%s\n};\n\n" % arr(KEY))
w("static const unsigned char ccm_vec_nonce[12] = {\n%s\n};\n\n" % arr(NONCE))
w("static const struct { unsigned payload, aad, tag_len; unsigned char tag[16]; }\n"
  "ccm_vec_cases[] = {\n")
for (p, a, t), tag in zip(cases, tags):
    w("    { %5u, %5u, %2u, { %s } },\n" % (p, a, t, ", ".join("0x%02x" % x for x in tag)))
w("};\n\n")
w("static const unsigned char ccm_vec_ciphertext[CCM_VEC_MAXLEN] = {\n%s\n};\n" % arr(full))
