#!/usr/bin/env python3
# AES-128-CCM known answers for test_ccm_contract.c, from an independent
# implementation: Python `cryptography` AESCCM (OpenSSL underneath).
#
#   python3 tests/ccm/gen_ccm_vectors.py > tests/ccm/ccm_vectors.h
#
# The plaintext and AAD are the patterns the test regenerates.  CTR output
# does not depend on the AAD or the tag length, and every plaintext is a
# prefix of the longest, so one ciphertext per nonce covers every case for
# that nonce; the generator asserts that rather than assuming it.
#
# SPDX-License-Identifier: MIT
import sys
import cryptography
from cryptography.hazmat.primitives.ciphers.aead import AESCCM
from cryptography.hazmat.backends.openssl.backend import backend

KEY = bytes(range(0x40, 0x50))
NONCE_BYTES = bytes(range(0x10, 0x1d))      # a nonce of n bytes is the first n
TAGS = [16, 8]

# (nonce length, payloads, AADs).  12 bytes is TLS (L = 3); 7 and 13 are the
# RFC 3610 ends, L = 8 and L = 2.
GROUPS = [
    (12, [0, 1, 16, 4080, 4096, 4112, 16384], [0, 5, 13]),
    (12, [0, 16, 4096], [65279, 65280, 70000]),   # last 2-octet l(a), first 6-octet, beyond
    (7,  [0, 16, 4080, 4096, 4112], [0, 13]),
    (13, [0, 16, 4080, 4096, 4112], [0, 13]),
]

def pt(n):  return bytes(((i * 31) + 7) & 0xFF for i in range(n))
def aad(n): return bytes(((i * 13) + 101) & 0xFF for i in range(n))

maxlen = {}
for nl, payloads, _ in GROUPS:
    maxlen[nl] = max(maxlen.get(nl, 0), max(payloads))

full = {}
for nl, m in maxlen.items():
    full[nl] = AESCCM(KEY, tag_length=16).encrypt(NONCE_BYTES[:nl], pt(m), None)[:m]

cases = []
for nl, payloads, aads in GROUPS:
    nonce = NONCE_BYTES[:nl]
    for p in payloads:
        for a in aads:
            for t in TAGS:
                ad = aad(a) if a else None
                out = AESCCM(KEY, tag_length=t).encrypt(nonce, pt(p), ad)
                assert out[:p] == full[nl][:p]
                assert AESCCM(KEY, tag_length=t).decrypt(nonce, out, ad) == pt(p)
                cases.append((nl, p, a, t, out[p:]))

def arr(b, ind="    "):
    return "\n".join(ind + ", ".join("0x%02x" % x for x in b[i:i + 12]) + ","
                     for i in range(0, len(b), 12))

w = sys.stdout.write
w("/* Generated by tests/ccm/gen_ccm_vectors.py: Python %s, cryptography %s, %s.\n"
  "   Do not edit. */\n\n" % (sys.version.split()[0], cryptography.__version__,
                              backend.openssl_version_text()))
w("#define CCM_VEC_MAXLEN %d\n\n" % max(maxlen.values()))
w("static const unsigned char ccm_vec_key[16] = {\n%s\n};\n\n" % arr(KEY))
w("static const unsigned char ccm_vec_nonce[13] = {\n%s\n};\n\n" % arr(NONCE_BYTES))
for nl in sorted(maxlen):
    w("static const unsigned char ccm_vec_ct%d[%d] = {\n%s\n};\n\n" % (nl, maxlen[nl], arr(full[nl])))
w("static const struct { unsigned nonce_len, payload, aad, tag_len; unsigned char tag[16]; }\n"
  "ccm_vec_cases[] = {\n")
for nl, p, a, t, tag in cases:
    w("    { %2u, %5u, %5u, %2u, { %s } },\n" % (nl, p, a, t, ", ".join("0x%02x" % x for x in tag)))
w("};\n\n")
w("static const unsigned char *ccm_vec_ciphertext(unsigned nonce_len)\n{\n")
for nl in sorted(maxlen):
    w("    if (nonce_len == %d) return ccm_vec_ct%d;\n" % (nl, nl))
w("    return 0;\n}\n")
