#!/usr/bin/env bash
#
# The synthetic arm: sockets driven directly, and the four blocking-socket
# probes.
#
#   tests/endurance/run-endurance.sh [-t SECONDS] [-c CONNS] [-k MHZ]
#                                    [-m MODEL] [-T TAG] [-b BUILDDIR]
#                                    [-s SAMPLE] [-P]
#
# SPDX-License-Identifier: MIT

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)

SECONDS_RUN=900
CONNS=2
MODEL=A1200
CLOCK=""
TAG="${AMINETXDUO_RUN_TAG:-endur}"
BUILD="${AMINETXDUO_BUILD:-build/cm}"
SAMPLE=15
PROBES=1
MODE=loop

while getopts "t:c:k:m:T:b:s:M:P" opt; do
    case "$opt" in
        t) SECONDS_RUN="$OPTARG" ;;
        c) CONNS="$OPTARG" ;;
        k) CLOCK="$OPTARG" ;;
        m) MODEL="$OPTARG" ;;
        T) TAG="$OPTARG" ;;
        b) BUILD="$OPTARG" ;;
        s) SAMPLE="$OPTARG" ;;
        M) MODE="$OPTARG" ;;
        P) PROBES=0 ;;
        *) echo "usage: $0 [-t secs] [-c conns] [-k MHz] [-m model]" \
                "[-T tag] [-b build] [-s sample] [-M loop|leak] [-P]" >&2
           exit 2 ;;
    esac
done

OUT="$ROOT/build/endurance"
BSD="$ROOT/$BUILD/src/bsdsocket/bsdsocket.library"
UG="$ROOT/$BUILD/src/usergroup/usergroup.library"

for f in "$OUT/Endurance" "$BSD"; do
    [ -f "$f" ] || { echo "missing $f, build the tree and run " \
                          "tests/endurance/build.sh" >&2; exit 2; }
done

A2065="${AMINETXDUO_A2065:-}"
if [ -z "$A2065" ]; then
    for candidate in \
        "$ROOT/build/a2065.device" \
        "$HOME/amiga-os-src/os-source/other_networking/sana2/bin/devs/a2065.device"
    do
        [ -f "$candidate" ] && { A2065="$candidate"; break; }
    done
fi
[ -n "$A2065" ] && [ -f "$A2065" ] || {
    echo "No a2065.device found. Set AMINETXDUO_A2065=<path>." >&2
    exit 2
}

STAGE="$ROOT/build/endurance-stage-$TAG"
rm -rf "$STAGE"
mkdir -p "$STAGE/libs"
cp -R "$ROOT/tests/netstack/devs" "$STAGE/devs"
cp "$A2065" "$STAGE/devs/a2065.device"
cp "$BSD" "$STAGE/libs/bsdsocket.library"
[ -f "$UG" ] && cp "$UG" "$STAGE/libs/usergroup.library"

cat > "$STAGE/endurance.cfg" <<EOF
# generated by tests/endurance/run-endurance.sh
mode $MODE
seconds $SECONDS_RUN
sample $SAMPLE
conns $CONNS
hogs 4
probes $PROBES
port 7801
maxio 32768
maxxfer 262144
maxecho 16384
churn 20
nbevery 50
seed 20260726
EOF

BASEDIR="$ROOT/build/fsuae-base-$TAG"
mkdir -p "$BASEDIR/Configurations"
cat > "$BASEDIR/Configurations/Host.fs-uae" <<'EOF'
[fs-uae]
floppy_drive_volume = 0
floppy_drive_volume_empty = 0
bsdsocket_library = 0
EOF

export AMINETXDUO_RUN_TAG="$TAG"

DEADLINE=$((SECONDS_RUN + 300))

CLOCKARG=()
[ -z "$CLOCK" ] || CLOCKARG=(-k "$CLOCK")

echo "==> $SECONDS_RUN s, mode $MODE, $CONNS connection(s), probes=$PROBES"

set +e
"$ROOT/tools/amiberry-run.sh" -N a2065 -m "$MODEL" -t "$DEADLINE" "${CLOCKARG[@]}" \
    "$OUT/Endurance" "$STAGE/devs" "$STAGE/libs" "$STAGE/endurance.cfg"
RUN_RC=$?
set -e

HD="$ROOT/build/amiberry-testhd-$TAG"

echo
echo "=== summary ==="
[ -f "$HD/end-summary.txt" ] && cat "$HD/end-summary.txt" || echo "(none)"

echo
echo "=== probes and events ==="
if [ -s "$HD/end-events.txt" ]; then
    grep -n "P3\|STALLED\|CORRUPT\|DESYNC" "$HD/end-events.txt" | head -20 || true
    echo "  --- every errno, with the socket's blocking state ---"
    awk '{ for (i = 1; i <= NF; i++) if ($i ~ /^blocking=/) b = $i;
           if (b == "blocking=1") n1++; else if (b == "blocking=0") n0++ }
         END { printf "  on a BLOCKING socket:     %d\n", n1;
               printf "  on a non-blocking socket: %d\n", n0 }' \
        "$HD/end-events.txt"
    grep "blocking=1" "$HD/end-events.txt" | head -20 || true
else
    echo "  (no events at all)"
fi

echo
echo "=== pool timeline ==="
if [ -f "$HD/end-timeline.csv" ]; then
    python3 "$ROOT/tests/endurance/endreport.py" "$HD/end-timeline.csv" || true
else
    echo "  (none)"
fi

exit "$RUN_RC"
