#!/usr/bin/env bash
#
# Hours of Fitz traffic, with the packet pool on a timeline.
#
#   tests/endurance/run-fitz.sh [-t SECONDS] [-k MHZ] [-m MODEL] [-T TAG]
#                               [-b BUILDDIR] [-f FILERS] [-s SAMPLE] [-r]
#
# SPDX-License-Identifier: MIT

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)

SECONDS_RUN=1800
MODEL=A1200
CLOCK=""
TAG="${AMINETXDUO_RUN_TAG:-fitz}"
BUILD="${AMINETXDUO_BUILD:-build/cm}"
FILERS=2
SAMPLE=15
RELEASED=0
PORT="${AMINETXDUO_FITZ_PORT:-17711}"
MAXXFER=262144
MAXIO=32768

while getopts "t:k:m:T:b:f:s:p:x:r" opt; do
    case "$opt" in
        t) SECONDS_RUN="$OPTARG" ;;
        k) CLOCK="$OPTARG" ;;
        m) MODEL="$OPTARG" ;;
        T) TAG="$OPTARG" ;;
        b) BUILD="$OPTARG" ;;
        f) FILERS="$OPTARG" ;;
        s) SAMPLE="$OPTARG" ;;
        p) PORT="$OPTARG" ;;
        x) MAXXFER="$OPTARG" ;;
        r) RELEASED=1 ;;
        *) echo "usage: $0 [-t secs] [-k MHz] [-m model] [-T tag] [-b build]" \
                "[-f filers] [-s sample] [-p port] [-x maxxfer] [-r]" >&2
           exit 2 ;;
    esac
done

OUT="$ROOT/build/endurance"
BSD="$ROOT/$BUILD/src/bsdsocket/bsdsocket.library"
UG="$ROOT/$BUILD/src/usergroup/usergroup.library"
SMOKE="$ROOT/$BUILD/src/tools/ToolsSmoke"
ADDIF="$ROOT/$BUILD/src/tools/AddNetInterface"

for f in "$OUT/Endurance" "$OUT/fitz-serve" "$BSD" "$SMOKE" "$ADDIF"; do
    [ -f "$f" ] || { echo "missing $f, build the tree and run " \
                          "tests/endurance/build.sh" >&2; exit 2; }
done

if [ "$RELEASED" = "1" ]; then
    AMIGA_FITZ="$OUT/fitz-release"
else
    AMIGA_FITZ="$OUT/fitz-debug"
fi
[ -f "$AMIGA_FITZ" ] || { echo "missing $AMIGA_FITZ" >&2; exit 2; }

# ---- a2065.device --------------------------------------------------------

A2065="${AMINETXDUO_A2065:-}"
if [ -z "$A2065" ]; then
    for candidate in \
        "$ROOT/build/a2065.device" \
        "$HOME/amiga-os-src/os-source/other_networking/sana2/bin/devs/a2065.device"
    do
        [ -f "$candidate" ] && { A2065="$candidate"; break; }
    done
fi
[ -n "$A2065" ] && [ -f "$A2065" ] || {
    echo "No a2065.device found. Set AMINETXDUO_A2065=<path>." >&2
    exit 2
}

# ---- the host server -----------------------------------------------------

SHARE="$ROOT/build/endurance-share-$TAG"
rm -rf "$SHARE"
mkdir -p "$SHARE"

PEERLOG="$ROOT/build/endurance-$TAG-peer.log"
: > "$PEERLOG"

"$OUT/fitz-serve" "$SHARE" PORT "$PORT" > "$PEERLOG" 2>&1 &
PEER_PID=$!

cleanup_peer() { kill -TERM "$PEER_PID" 2>/dev/null || true; }
trap cleanup_peer EXIT INT TERM HUP

sleep 1
kill -0 "$PEER_PID" 2>/dev/null || {
    echo "fitz-serve did not start:" >&2
    cat "$PEERLOG" >&2
    exit 2
}
echo "==> fitz-serve on port $PORT sharing $SHARE (pid $PEER_PID)"

# ---- stage the guest -----------------------------------------------------

STAGE="$ROOT/build/endurance-stage-$TAG"
rm -rf "$STAGE"
mkdir -p "$STAGE/libs"
cp -R "$ROOT/tests/netstack/devs" "$STAGE/devs"
cp "$A2065" "$STAGE/devs/a2065.device"
cp "$BSD" "$STAGE/libs/bsdsocket.library"
[ -f "$UG" ] && cp "$UG" "$STAGE/libs/usergroup.library"
cp "$AMIGA_FITZ" "$STAGE/fitz"
cp "$OUT/Endurance" "$STAGE/Endurance"
cp "$ADDIF" "$STAGE/AddNetInterface"

cat > "$STAGE/endurance.cfg" <<EOF
# generated by tests/endurance/run-fitz.sh
mode fitz
path FITZ:
seconds $SECONDS_RUN
sample $SAMPLE
filers $FILERS
maxio $MAXIO
maxxfer $MAXXFER
probes 0
seed 20260726
EOF

{
    echo "# generated by tests/endurance/run-fitz.sh"
    echo "SYS:AddNetInterface eth0"
    echo "wait 4"
    echo "&SYS:fitz mount 10.0.2.2:$PORT FITZ:"
    echo "wait 10"
    echo "SYS:Endurance"
} > "$STAGE/commands.txt"

export AMINETXDUO_RUN_TAG="$TAG"

DEADLINE=$((SECONDS_RUN + 300))

echo "==> run:  $SECONDS_RUN s workload, $DEADLINE s emulator deadline"
echo "==> fitz: $(basename "$AMIGA_FITZ")"

CLOCKARG=()
[ -z "$CLOCK" ] || CLOCKARG=(-k "$CLOCK")

set +e
"$ROOT/tools/amiberry-run.sh" -N a2065 -m "$MODEL" -t "$DEADLINE" "${CLOCKARG[@]}" \
    "$SMOKE" "$STAGE/devs" "$STAGE/libs" "$STAGE/fitz" "$STAGE/Endurance" \
    "$STAGE/AddNetInterface" "$STAGE/commands.txt" "$STAGE/endurance.cfg"
RUN_RC=$?
set -e

# ---- what came back ------------------------------------------------------

HD="$ROOT/build/amiberry-testhd-$TAG"

echo
echo "=== summary ==="
[ -f "$HD/end-summary.txt" ] && cat "$HD/end-summary.txt" || echo "(none written)"

echo
echo "=== errors and events ==="
if [ -s "$HD/end-events.txt" ]; then
    wc -l < "$HD/end-events.txt" | tr -d ' ' | sed 's/^/  lines: /'
    head -40 "$HD/end-events.txt"
else
    echo "  (none)"
fi

echo
echo "=== Fitz's own diagnostics (serial) ==="
# build/serial-<tag>.log is a path amiberry-run.sh has never written, so these
# counts were never once taken and the absence read as a clean run.
. "$ROOT/tools/serial-log.sh"
SER=$(serial_log_path "$TAG")
if serial_log_have "$SER" "$BUILD" "Fitz's EAGAIN and send/recv counts"; then
    EAGAIN=$(grep -c "EAGAIN" "$SER" || true)
    SERR=$(grep -cE "send error|recv error|recv maxretry" "$SER" || true)
    echo "  EAGAIN on a blocking socket: $EAGAIN"
    echo "  send/recv failures:          $SERR"
    grep -nE "EAGAIN|send error|recv error|recv maxretry" "$SER" | head -20 || true
else
    SERIAL_UNCHECKED=1
fi

echo
echo "=== pool timeline ==="
if [ -f "$HD/end-timeline.csv" ]; then
    python3 "$ROOT/tests/endurance/endreport.py" "$HD/end-timeline.csv" || true
else
    echo "  (none written)"
fi

# An empty serial log means the diagnostics above were NOT taken.  Exit 2, the
# tree's missing-ingredient code, so it can never be read as a clean run.
[ "$RUN_RC" = 0 ] || exit "$RUN_RC"
[ "${SERIAL_UNCHECKED:-0}" = 0 ] || exit 2
exit 0
