#!/usr/bin/env bash
#
# A file with a generator is not a file you edit.
#
#   tools/check-generated.sh            check what git has staged
#   tools/check-generated.sh --all      check the files whatever is staged
#
# src/bsdsocket/bsdsocket_vectors.[ch] say "GENERATED by tools/gen_vectors.py.
# Do not edit." on line 4 and are built from the Roadshow NDK pragmas.  Editing
# them by hand still compiles, still links, and still passes the host tier --
# the reproduce check lives in the CROSS stage (tools/ci.sh:935), so the first
# thing that notices is a twelve minute CI cycle.  That is what happened to
# vsyslog: three green local host runs, then red.
#
# It costs about a second here, so it runs at commit time instead.
#
# THE NDK IS REQUIRED AND MAY BE ABSENT.  A checkout with no toolchain cannot
# verify this, and a gate that fails because it cannot see is a gate people
# learn to bypass; it says `skipped` and why.  CI always has the toolchain, so
# nothing is lost there.
#
# SPDX-License-Identifier: MIT

set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
MODE="${1:-staged}"

GENERATED="src/bsdsocket/bsdsocket_vectors.c src/bsdsocket/bsdsocket_vectors.h"

if [ "$MODE" = "--all" ]; then
    touched="$GENERATED"
else
    staged=$(git diff --cached --name-only 2>/dev/null || true)
    touched=""
    for f in $GENERATED; do
        case " $staged " in *" $f "*) touched="$touched $f" ;; esac
    done
fi

if [ -z "${touched// /}" ]; then
    echo "generated=ok reason=none_staged"
    exit 0
fi

ndk="${AMIGA_TOOLCHAIN_ROOT:-}/m68k-amigaos/ndk-include"
if [ ! -d "$ndk" ]; then
    ndk=$(ls -d "$HOME"/.cache/aminetxduo/toolchain/*/m68k-amigaos/ndk-include \
          2>/dev/null | head -1 || true)
fi
if [ -z "$ndk" ] || [ ! -d "$ndk" ]; then
    echo "generated=skipped reason=no_ndk files=$(echo $touched | wc -w)"
    exit 0
fi

if python3 tools/gen_vectors.py --ndk "$ndk" --check > /tmp/gen-check.$$ 2>&1; then
    echo "generated=PASS files=$(echo $touched | wc -w) $(tail -1 /tmp/gen-check.$$)"
    rm -f /tmp/gen-check.$$
    exit 0
fi

cat /tmp/gen-check.$$
rm -f /tmp/gen-check.$$
echo "generated=FAIL reason=hand_edited files=$(echo $touched)"
echo "  these are OUTPUT.  Change tools/gen_vectors.py and regenerate:"
echo "    python3 tools/gen_vectors.py --ndk \"$ndk\""
exit 1
