#!/usr/bin/env python3
"""Turn one PEM certificate into the C array tests/tls/tls_https.c compiles in.

    tools/mkroothdr.py root.pem > tests/tls/tls_root_local.h

Only for pointing that test at tests/peer/mkpki.sh's local PKI, where the
chain is two deep and verifies at 14 MHz.  The shipped trust store is built by
tools/mkcertstore.py and is a different thing entirely.
"""
import base64
import sys

pem = open(sys.argv[1]).read()
body = pem.split("-----BEGIN CERTIFICATE-----")[1].split("-----END CERTIFICATE-----")[0]
der = base64.b64decode("".join(body.split()))

print("/* Generated by tools/mkroothdr.py from %s.  Do not edit. */" % sys.argv[1])
print("#ifndef AMINETXDUO_TLS_ROOT_LOCAL_H")
print("#define AMINETXDUO_TLS_ROOT_LOCAL_H")
print()
print("static const unsigned char w_root_local_der[] =")
print("{")
for i in range(0, len(der), 12):
    print("    " + " ".join("0x%02x," % b for b in der[i:i + 12]))
print("};")
print()
print("#define w_root_local_der_len    ((unsigned short)sizeof(w_root_local_der))")
print()
print("#endif")
