/*
 * bsdsocket.library -- LVO vector declarations.
 *
 * GENERATED by tools/gen_vectors.py from the Roadshow NDK headers
 * (pragmas/bsdsocket_pragmas.h + clib/bsdsocket_protos.h).  Do not edit;
 * re-run the generator instead.
 *
 * Every vector is declared with the exact m68k register assignment the ABI
 * specifies, plus the library base in a6.  Implementations in src/bsdsocket
 * include this header, so the compiler checks each definition against the
 * ABI rather than against a hand-copied signature.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef AMINETXDUO_BSDSOCKET_VECTORS_H
#define AMINETXDUO_BSDSOCKET_VECTORS_H

#include "bsdsocket_internal.h"

#include <sys/mbuf.h>
#include <net/route.h>

/* The shared stubs every unimplemented slot points at: they set errno to
 * ENOSYS and return the "failed" value for their shape.  Never NULL in the
 * table -- a jump through a NULL LVO takes the machine down, and Tier-3
 * vectors do get called by stock Roadshow tools.
 *
 * Three of them because the shapes differ.  A vector documented to return a
 * pointer must return NULL on failure, not -1: its callers test for NULL and
 * then dereference, so a -1 stub turns "unimplemented" into a guru inside the
 * application.  A vector documented to return BOOL must return FALSE, because
 * -1 is all-bits-set and every BOOL test reads that as TRUE -- a -1 stub for
 * ProcessIsServer() or ChangeRoadshowData() reports SUCCESS. */
LONG bsd_enosys(register struct AmiSocketBase *SocketBase __asm("a6"));
APTR bsd_enosys_ptr(register struct AmiSocketBase *SocketBase __asm("a6"));
BOOL bsd_enosys_bool(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x01e */
LONG bsd_socket(register LONG domain __asm("d0"),
                register LONG type __asm("d1"),
                register LONG protocol __asm("d2"),
                register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x024 */
LONG bsd_bind(register LONG sock __asm("d0"),
              register struct sockaddr *name __asm("a0"),
              register socklen_t namelen __asm("d1"),
              register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x02a */
LONG bsd_listen(register LONG sock __asm("d0"),
                register LONG backlog __asm("d1"),
                register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x030 */
LONG bsd_accept(register LONG sock __asm("d0"),
                register struct sockaddr *addr __asm("a0"),
                register socklen_t *addrlen __asm("a1"),
                register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x036 */
LONG bsd_connect(register LONG sock __asm("d0"),
                 register struct sockaddr *name __asm("a0"),
                 register socklen_t namelen __asm("d1"),
                 register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x03c */
LONG bsd_sendto(register LONG sock __asm("d0"),
                register APTR buf __asm("a0"),
                register LONG len __asm("d1"),
                register LONG flags __asm("d2"),
                register struct sockaddr *to __asm("a1"),
                register socklen_t tolen __asm("d3"),
                register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x042 */
LONG bsd_send(register LONG sock __asm("d0"),
              register APTR buf __asm("a0"),
              register LONG len __asm("d1"),
              register LONG flags __asm("d2"),
              register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x048 */
LONG bsd_recvfrom(register LONG sock __asm("d0"),
                  register APTR buf __asm("a0"),
                  register LONG len __asm("d1"),
                  register LONG flags __asm("d2"),
                  register struct sockaddr *addr __asm("a1"),
                  register socklen_t *addrlen __asm("a2"),
                  register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x04e */
LONG bsd_recv(register LONG sock __asm("d0"),
              register APTR buf __asm("a0"),
              register LONG len __asm("d1"),
              register LONG flags __asm("d2"),
              register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x054 */
LONG bsd_shutdown(register LONG sock __asm("d0"),
                  register LONG how __asm("d1"),
                  register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x05a */
LONG bsd_setsockopt(register LONG sock __asm("d0"),
                    register LONG level __asm("d1"),
                    register LONG optname __asm("d2"),
                    register APTR optval __asm("a0"),
                    register socklen_t optlen __asm("d3"),
                    register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x060 */
LONG bsd_getsockopt(register LONG sock __asm("d0"),
                    register LONG level __asm("d1"),
                    register LONG optname __asm("d2"),
                    register APTR optval __asm("a0"),
                    register socklen_t *optlen __asm("a1"),
                    register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x066 */
LONG bsd_getsockname(register LONG sock __asm("d0"),
                     register struct sockaddr *name __asm("a0"),
                     register socklen_t *namelen __asm("a1"),
                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x06c */
LONG bsd_getpeername(register LONG sock __asm("d0"),
                     register struct sockaddr *name __asm("a0"),
                     register socklen_t *namelen __asm("a1"),
                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x072 */
LONG bsd_IoctlSocket(register LONG sock __asm("d0"),
                     register ULONG req __asm("d1"),
                     register APTR argp __asm("a0"),
                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x078 */
LONG bsd_CloseSocket(register LONG sock __asm("d0"),
                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x07e */
LONG bsd_WaitSelect(register LONG nfds __asm("d0"),
                    register APTR read_fds __asm("a0"),
                    register APTR write_fds __asm("a1"),
                    register APTR except_fds __asm("a2"),
                    register struct timeval *timeout __asm("a3"),
                    register ULONG *signals __asm("d1"),
                    register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x084 */
VOID bsd_SetSocketSignals(register ULONG int_mask __asm("d0"),
                          register ULONG io_mask __asm("d1"),
                          register ULONG urgent_mask __asm("d2"),
                          register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x08a */
int bsd_getdtablesize(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x090 */
LONG bsd_ObtainSocket(register LONG id __asm("d0"),
                      register LONG domain __asm("d1"),
                      register LONG type __asm("d2"),
                      register LONG protocol __asm("d3"),
                      register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x096 */
LONG bsd_ReleaseSocket(register LONG sock __asm("d0"),
                       register LONG id __asm("d1"),
                       register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x09c */
LONG bsd_ReleaseCopyOfSocket(register LONG sock __asm("d0"),
                             register LONG id __asm("d1"),
                             register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0a2 */
LONG bsd_Errno(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0a8 */
VOID bsd_SetErrnoPtr(register APTR errno_ptr __asm("a0"),
                     register LONG size __asm("d0"),
                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0ae */
STRPTR bsd_Inet_NtoA(register in_addr_t ip __asm("d0"),
                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0b4 */
in_addr_t bsd_inet_addr(register STRPTR cp __asm("a0"),
                        register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0ba */
in_addr_t bsd_Inet_LnaOf(register in_addr_t in __asm("d0"),
                         register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0c0 */
in_addr_t bsd_Inet_NetOf(register in_addr_t in __asm("d0"),
                         register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0c6 */
in_addr_t bsd_Inet_MakeAddr(register in_addr_t net __asm("d0"),
                            register in_addr_t host __asm("d1"),
                            register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0cc */
in_addr_t bsd_inet_network(register STRPTR cp __asm("a0"),
                           register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0d2 */
struct hostent *bsd_gethostbyname(register STRPTR name __asm("a0"),
                                  register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0d8 */
struct hostent *bsd_gethostbyaddr(register STRPTR addr __asm("a0"),
                                  register LONG len __asm("d0"),
                                  register LONG type __asm("d1"),
                                  register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0de */
struct netent *bsd_getnetbyname(register STRPTR name __asm("a0"),
                                register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0e4 */
struct netent *bsd_getnetbyaddr(register in_addr_t net __asm("d0"),
                                register LONG type __asm("d1"),
                                register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0ea */
struct servent *bsd_getservbyname(register STRPTR name __asm("a0"),
                                  register STRPTR proto __asm("a1"),
                                  register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0f0 */
struct servent *bsd_getservbyport(register LONG port __asm("d0"),
                                  register STRPTR proto __asm("a0"),
                                  register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0f6 */
struct protoent *bsd_getprotobyname(register STRPTR name __asm("a0"),
                                    register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x0fc */
struct protoent *bsd_getprotobynumber(register LONG proto __asm("d0"),
                                      register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x108 */
LONG bsd_Dup2Socket(register LONG old_socket __asm("d0"),
                    register LONG new_socket __asm("d1"),
                    register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x10e */
LONG bsd_sendmsg(register LONG sock __asm("d0"),
                 register struct msghdr *msg __asm("a0"),
                 register LONG flags __asm("d1"),
                 register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x114 */
LONG bsd_recvmsg(register LONG sock __asm("d0"),
                 register struct msghdr *msg __asm("a0"),
                 register LONG flags __asm("d1"),
                 register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x11a */
int bsd_gethostname(register char *name __asm("a0"),
                    register size_t namelen __asm("d0"),
                    register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x120 */
long bsd_gethostid(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x126 */
LONG bsd_SocketBaseTagList(register struct TagItem *tags __asm("a0"),
                           register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x12c */
LONG bsd_GetSocketEvents(register ULONG *event_ptr __asm("a0"),
                         register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x210 */
VOID bsd_ReleaseDomainNameServerList(register struct List *list __asm("a0"),
                                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x216 */
struct List *bsd_ObtainDomainNameServerList(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x21c */
VOID bsd_setnetent(register LONG stay_open __asm("d0"),
                   register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x222 */
VOID bsd_endnetent(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x228 */
struct netent *bsd_getnetent(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x22e */
VOID bsd_setprotoent(register LONG stay_open __asm("d0"),
                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x234 */
VOID bsd_endprotoent(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x23a */
struct protoent *bsd_getprotoent(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x240 */
VOID bsd_setservent(register LONG stay_open __asm("d0"),
                    register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x246 */
VOID bsd_endservent(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x24c */
struct servent *bsd_getservent(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x252 */
LONG bsd_inet_aton(register STRPTR cp __asm("a0"),
                   register struct in_addr *addr __asm("a1"),
                   register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x258 */
STRPTR bsd_inet_ntop(register LONG af __asm("d0"),
                     register APTR src __asm("a0"),
                     register STRPTR dst __asm("a1"),
                     register LONG size __asm("d1"),
                     register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x25e */
LONG bsd_inet_pton(register LONG af __asm("d0"),
                   register STRPTR src __asm("a0"),
                   register APTR dst __asm("a1"),
                   register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x264 */
LONG bsd_In_LocalAddr(register in_addr_t address __asm("d0"),
                      register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x26a */
LONG bsd_In_CanForward(register in_addr_t address __asm("d0"),
                       register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x2b2 */
BOOL bsd_ProcessIsServer(register struct Process *pr __asm("a0"),
                         register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x2b8 */
LONG bsd_ObtainServerSocket(register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x2be */
BOOL bsd_GetDefaultDomainName(register STRPTR buffer __asm("a0"),
                              register LONG buffer_size __asm("d0"),
                              register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x2e2 */
struct hostent *bsd_gethostbyname_r(register STRPTR name __asm("a0"),
                                    register struct hostent *hp __asm("a1"),
                                    register APTR buf __asm("a2"),
                                    register ULONG buflen __asm("d0"),
                                    register LONG *he __asm("a3"),
                                    register struct AmiSocketBase *SocketBase __asm("a6"));

/* LVO -0x2e8 */
struct hostent *bsd_gethostbyaddr_r(register STRPTR addr __asm("a0"),
                                    register LONG len __asm("d0"),
                                    register LONG type __asm("d1"),
                                    register struct hostent *hp __asm("a1"),
                                    register APTR buf __asm("a2"),
                                    register ULONG buflen __asm("d2"),
                                    register LONG *he __asm("a3"),
                                    register struct AmiSocketBase *SocketBase __asm("a6"));


/* The vector table itself, terminated by (APTR)-1, as MakeLibrary wants it. */
extern const APTR BsdVectorTable[];

#endif /* AMINETXDUO_BSDSOCKET_VECTORS_H */
