/*
 * bsdsocket.library, the LVO vector table.
 *
 * GENERATED by tools/gen_vectors.py.  Do not edit.
 *
 * MakeLibrary() lays these out at 6 bytes per entry going down from the
 * library base, so entry i sits at LVO -(6 * (i + 1)).  The first four are
 * the exec standard set; user vector n is at index (offset / 6) - 1.
 *
 * The table is dense: slots the ABI reserves (0x132..0x168 and the two after
 * gethostbyaddr_r) and every vector not yet implemented point at bsd_enosys()
 * rather than NULL.
 *
 * Coverage: 139 ABI vectors (121 named, 18 reserved/private), 99 implemented, 41 stubbed (7 of them NULL-returning, 1 FALSE-returning).
 *
 * SPDX-License-Identifier: MIT
 */

#include "bsdsocket_vectors.h"

/* Function pointers of assorted shapes go into one table; exec only ever
 * copies them into JMP instructions, so the C type is irrelevant. */
typedef VOID (*BsdVector)(VOID);

const APTR BsdVectorTable[] =
{
    /* -6 Open, -12 Close, -18 Expunge, -24 Reserved */
    (APTR)bsd_lib_open,
    (APTR)bsd_lib_close,
    (APTR)bsd_lib_expunge,
    (APTR)bsd_lib_reserved,

    (APTR)bsd_socket,             /* -0x01e [  4] socket */
    (APTR)bsd_bind,               /* -0x024 [  5] bind */
    (APTR)bsd_listen,             /* -0x02a [  6] listen */
    (APTR)bsd_accept,             /* -0x030 [  7] accept */
    (APTR)bsd_connect,            /* -0x036 [  8] connect */
    (APTR)bsd_sendto,             /* -0x03c [  9] sendto */
    (APTR)bsd_send,               /* -0x042 [ 10] send */
    (APTR)bsd_recvfrom,           /* -0x048 [ 11] recvfrom */
    (APTR)bsd_recv,               /* -0x04e [ 12] recv */
    (APTR)bsd_shutdown,           /* -0x054 [ 13] shutdown */
    (APTR)bsd_setsockopt,         /* -0x05a [ 14] setsockopt */
    (APTR)bsd_getsockopt,         /* -0x060 [ 15] getsockopt */
    (APTR)bsd_getsockname,        /* -0x066 [ 16] getsockname */
    (APTR)bsd_getpeername,        /* -0x06c [ 17] getpeername */
    (APTR)bsd_IoctlSocket,        /* -0x072 [ 18] IoctlSocket */
    (APTR)bsd_CloseSocket,        /* -0x078 [ 19] CloseSocket */
    (APTR)bsd_WaitSelect,         /* -0x07e [ 20] WaitSelect */
    (APTR)bsd_SetSocketSignals,   /* -0x084 [ 21] SetSocketSignals */
    (APTR)bsd_getdtablesize,      /* -0x08a [ 22] getdtablesize */
    (APTR)bsd_ObtainSocket,       /* -0x090 [ 23] ObtainSocket */
    (APTR)bsd_ReleaseSocket,      /* -0x096 [ 24] ReleaseSocket */
    (APTR)bsd_ReleaseCopyOfSocket, /* -0x09c [ 25] ReleaseCopyOfSocket */
    (APTR)bsd_Errno,              /* -0x0a2 [ 26] Errno */
    (APTR)bsd_SetErrnoPtr,        /* -0x0a8 [ 27] SetErrnoPtr */
    (APTR)bsd_Inet_NtoA,          /* -0x0ae [ 28] Inet_NtoA */
    (APTR)bsd_inet_addr,          /* -0x0b4 [ 29] inet_addr */
    (APTR)bsd_Inet_LnaOf,         /* -0x0ba [ 30] Inet_LnaOf */
    (APTR)bsd_Inet_NetOf,         /* -0x0c0 [ 31] Inet_NetOf */
    (APTR)bsd_Inet_MakeAddr,      /* -0x0c6 [ 32] Inet_MakeAddr */
    (APTR)bsd_inet_network,       /* -0x0cc [ 33] inet_network */
    (APTR)bsd_gethostbyname,      /* -0x0d2 [ 34] gethostbyname */
    (APTR)bsd_gethostbyaddr,      /* -0x0d8 [ 35] gethostbyaddr */
    (APTR)bsd_getnetbyname,       /* -0x0de [ 36] getnetbyname */
    (APTR)bsd_getnetbyaddr,       /* -0x0e4 [ 37] getnetbyaddr */
    (APTR)bsd_getservbyname,      /* -0x0ea [ 38] getservbyname */
    (APTR)bsd_getservbyport,      /* -0x0f0 [ 39] getservbyport */
    (APTR)bsd_getprotobyname,     /* -0x0f6 [ 40] getprotobyname */
    (APTR)bsd_getprotobynumber,   /* -0x0fc [ 41] getprotobynumber */
    (APTR)bsd_enosys,             /* -0x102 [ 42] vsyslog */
    (APTR)bsd_Dup2Socket,         /* -0x108 [ 43] Dup2Socket */
    (APTR)bsd_sendmsg,            /* -0x10e [ 44] sendmsg */
    (APTR)bsd_recvmsg,            /* -0x114 [ 45] recvmsg */
    (APTR)bsd_gethostname,        /* -0x11a [ 46] gethostname */
    (APTR)bsd_gethostid,          /* -0x120 [ 47] gethostid */
    (APTR)bsd_SocketBaseTagList,  /* -0x126 [ 48] SocketBaseTagList */
    (APTR)bsd_GetSocketEvents,    /* -0x12c [ 49] GetSocketEvents */
    (APTR)bsd_enosys,                    /* -0x132 [ 50] reserved */
    (APTR)bsd_enosys,                    /* -0x138 [ 51] reserved */
    (APTR)bsd_enosys,                    /* -0x13e [ 52] reserved */
    (APTR)bsd_enosys,                    /* -0x144 [ 53] reserved */
    (APTR)bsd_enosys,                    /* -0x14a [ 54] reserved */
    (APTR)bsd_enosys,                    /* -0x150 [ 55] reserved */
    (APTR)bsd_enosys,                    /* -0x156 [ 56] reserved */
    (APTR)bsd_enosys,                    /* -0x15c [ 57] reserved */
    (APTR)bsd_enosys,                    /* -0x162 [ 58] reserved */
    (APTR)bsd_enosys,                    /* -0x168 [ 59] reserved */
    (APTR)bsd_bpf_open,           /* -0x16e [ 60] bpf_open */
    (APTR)bsd_bpf_close,          /* -0x174 [ 61] bpf_close */
    (APTR)bsd_bpf_read,           /* -0x17a [ 62] bpf_read */
    (APTR)bsd_bpf_write,          /* -0x180 [ 63] bpf_write */
    (APTR)bsd_bpf_set_notify_mask, /* -0x186 [ 64] bpf_set_notify_mask */
    (APTR)bsd_bpf_set_interrupt_mask, /* -0x18c [ 65] bpf_set_interrupt_mask */
    (APTR)bsd_bpf_ioctl,          /* -0x192 [ 66] bpf_ioctl */
    (APTR)bsd_bpf_data_waiting,   /* -0x198 [ 67] bpf_data_waiting */
    (APTR)bsd_AddRouteTagList,    /* -0x19e [ 68] AddRouteTagList */
    (APTR)bsd_DeleteRouteTagList, /* -0x1a4 [ 69] DeleteRouteTagList */
    (APTR)bsd_ChangeRouteTagList, /* -0x1aa [ 70] ChangeRouteTagList */
    (APTR)bsd_FreeRouteInfo,      /* -0x1b0 [ 71] FreeRouteInfo */
    (APTR)bsd_GetRouteInfo,       /* -0x1b6 [ 72] GetRouteInfo */
    (APTR)bsd_AddInterfaceTagList, /* -0x1bc [ 73] AddInterfaceTagList */
    (APTR)bsd_ConfigureInterfaceTagList, /* -0x1c2 [ 74] ConfigureInterfaceTagList */
    (APTR)bsd_ReleaseInterfaceList, /* -0x1c8 [ 75] ReleaseInterfaceList */
    (APTR)bsd_ObtainInterfaceList, /* -0x1ce [ 76] ObtainInterfaceList */
    (APTR)bsd_QueryInterfaceTagList, /* -0x1d4 [ 77] QueryInterfaceTagList */
    (APTR)bsd_CreateAddrAllocMessageA, /* -0x1da [ 78] CreateAddrAllocMessageA */
    (APTR)bsd_DeleteAddrAllocMessage, /* -0x1e0 [ 79] DeleteAddrAllocMessage */
    (APTR)bsd_BeginInterfaceConfig, /* -0x1e6 [ 80] BeginInterfaceConfig */
    (APTR)bsd_AbortInterfaceConfig, /* -0x1ec [ 81] AbortInterfaceConfig */
    (APTR)bsd_AddNetMonitorHookTagList, /* -0x1f2 [ 82] AddNetMonitorHookTagList */
    (APTR)bsd_RemoveNetMonitorHook, /* -0x1f8 [ 83] RemoveNetMonitorHook */
    (APTR)bsd_GetNetworkStatistics, /* -0x1fe [ 84] GetNetworkStatistics */
    (APTR)bsd_AddDomainNameServer, /* -0x204 [ 85] AddDomainNameServer */
    (APTR)bsd_RemoveDomainNameServer, /* -0x20a [ 86] RemoveDomainNameServer */
    (APTR)bsd_ReleaseDomainNameServerList, /* -0x210 [ 87] ReleaseDomainNameServerList */
    (APTR)bsd_ObtainDomainNameServerList, /* -0x216 [ 88] ObtainDomainNameServerList */
    (APTR)bsd_setnetent,          /* -0x21c [ 89] setnetent */
    (APTR)bsd_endnetent,          /* -0x222 [ 90] endnetent */
    (APTR)bsd_getnetent,          /* -0x228 [ 91] getnetent */
    (APTR)bsd_setprotoent,        /* -0x22e [ 92] setprotoent */
    (APTR)bsd_endprotoent,        /* -0x234 [ 93] endprotoent */
    (APTR)bsd_getprotoent,        /* -0x23a [ 94] getprotoent */
    (APTR)bsd_setservent,         /* -0x240 [ 95] setservent */
    (APTR)bsd_endservent,         /* -0x246 [ 96] endservent */
    (APTR)bsd_getservent,         /* -0x24c [ 97] getservent */
    (APTR)bsd_inet_aton,          /* -0x252 [ 98] inet_aton */
    (APTR)bsd_inet_ntop,          /* -0x258 [ 99] inet_ntop */
    (APTR)bsd_inet_pton,          /* -0x25e [100] inet_pton */
    (APTR)bsd_In_LocalAddr,       /* -0x264 [101] In_LocalAddr */
    (APTR)bsd_In_CanForward,      /* -0x26a [102] In_CanForward */
    (APTR)bsd_enosys_ptr,         /* -0x270 [103] mbuf_copym */
    (APTR)bsd_enosys,             /* -0x276 [104] mbuf_copyback */
    (APTR)bsd_enosys,             /* -0x27c [105] mbuf_copydata */
    (APTR)bsd_enosys_ptr,         /* -0x282 [106] mbuf_free */
    (APTR)bsd_enosys,             /* -0x288 [107] mbuf_freem */
    (APTR)bsd_enosys_ptr,         /* -0x28e [108] mbuf_get */
    (APTR)bsd_enosys_ptr,         /* -0x294 [109] mbuf_gethdr */
    (APTR)bsd_enosys_ptr,         /* -0x29a [110] mbuf_prepend */
    (APTR)bsd_enosys,             /* -0x2a0 [111] mbuf_cat */
    (APTR)bsd_enosys,             /* -0x2a6 [112] mbuf_adj */
    (APTR)bsd_enosys_ptr,         /* -0x2ac [113] mbuf_pullup */
    (APTR)bsd_ProcessIsServer,    /* -0x2b2 [114] ProcessIsServer */
    (APTR)bsd_ObtainServerSocket, /* -0x2b8 [115] ObtainServerSocket */
    (APTR)bsd_GetDefaultDomainName, /* -0x2be [116] GetDefaultDomainName */
    (APTR)bsd_SetDefaultDomainName, /* -0x2c4 [117] SetDefaultDomainName */
    (APTR)bsd_enosys_ptr,         /* -0x2ca [118] ObtainRoadshowData */
    (APTR)bsd_enosys,             /* -0x2d0 [119] ReleaseRoadshowData */
    (APTR)bsd_enosys_bool,        /* -0x2d6 [120] ChangeRoadshowData */
    (APTR)bsd_RemoveInterface,    /* -0x2dc [121] RemoveInterface */
    (APTR)bsd_gethostbyname_r,    /* -0x2e2 [122] gethostbyname_r */
    (APTR)bsd_gethostbyaddr_r,    /* -0x2e8 [123] gethostbyaddr_r */
    (APTR)bsd_enosys,                    /* -0x2ee [124] reserved */
    (APTR)bsd_enosys,                    /* -0x2f4 [125] reserved */
    (APTR)bsd_enosys,             /* -0x2fa [126] ipf_open */
    (APTR)bsd_enosys,             /* -0x300 [127] ipf_close */
    (APTR)bsd_enosys,             /* -0x306 [128] ipf_ioctl */
    (APTR)bsd_enosys,             /* -0x30c [129] ipf_log_read */
    (APTR)bsd_enosys,             /* -0x312 [130] ipf_log_data_waiting */
    (APTR)bsd_enosys,             /* -0x318 [131] ipf_set_notify_mask */
    (APTR)bsd_enosys,             /* -0x31e [132] ipf_set_interrupt_mask */
    (APTR)bsd_freeaddrinfo,       /* -0x324 [133] freeaddrinfo */
    (APTR)bsd_getaddrinfo,        /* -0x32a [134] getaddrinfo */
    (APTR)bsd_gai_strerror,       /* -0x330 [135] gai_strerror */
    (APTR)bsd_getnameinfo,        /* -0x336 [136] getnameinfo */
    (APTR)bsd_enosys,                    /* -0x33c [137] reserved */
    (APTR)bsd_enosys,                    /* -0x342 [138] reserved */
    (APTR)bsd_enosys,                    /* -0x348 [139] reserved */
    (APTR)bsd_enosys,                    /* -0x34e [140] reserved */
    (APTR)bsd_enosys,                    /* -0x354 [141] reserved */
    (APTR)bsd_enosys,                    /* -0x35a [142] reserved */

    (APTR)bsd_enosys,                    /* -0x360 [143] reserved, was bsd_ObtainNetXDuoContext */

    /* -0x366 [144] bsd_NetStackQuery, PRIVATE: a snapshot of the running stack, netstatus.h */
    (APTR)bsd_NetStackQuery,

    /* -0x36c [145] bsd_NetStackControl, PRIVATE: interfaces, routes and the ARP cache, netstatus.h */
    (APTR)bsd_NetStackControl,

    /*
     * -0x372 [146] onward, RFC 3493 section 4, PUBLIC, revision 3 and up.
     *
     * The first extension past the end of the NDK's table. Deliberately not
     * the ==reserve 6 block at -0x33c..-0x35a ([137]..[142] above): that is
     * what a regenerated SFD fills first, and six slots do not hold an
     * extension that will grow. docs/NDK-ADDENDUM.md.
     */
    (APTR)bsd_if_nametoindex,            /* -0x372 [146] if_nametoindex */
    (APTR)bsd_if_indextoname,            /* -0x378 [147] if_indextoname */
    (APTR)bsd_if_nameindex,              /* -0x37e [148] if_nameindex */
    (APTR)bsd_if_freenameindex,          /* -0x384 [149] if_freenameindex */

    (APTR)-1
};
