/*
 * bsdsocket.library, SOCK_RAW.
 *
 * This is not a wrapper around nx_ip_raw_packet_receive().
 *
 * NetX Duo has no raw socket object.  It has an IP-level raw service: one
 * queue per NX_IP, fed by _nx_ip_raw_packet_processing(), drained by whoever
 * calls nx_ip_raw_packet_receive() first.  Two things make that unusable as
 * the back end for a BSD descriptor:
 *
 *   1. ICMP never reaches it.  _nx_ip_dispatch_process() sends ICMPv4 to
 *      nx_ip_icmp_packet_receive and only consults the raw hook in the "I do
 *      not recognise this protocol" branch, so a raw socket opened with
 *      IPPROTO_ICMP, the one every ping and traceroute opens, would never
 *      see a byte.  NX_ENABLE_IP_RAW_PACKET_ALL_STACK (port nx_user.h) moves
 *      the hook to the top of the dispatch, ahead of TCP, UDP, ICMP and IGMP.
 *
 *   2. That hook is the filter, and installing a filter turns the queue off
 *      entirely: _nx_ip_raw_packet_processing() returns as soon as it sees one
 *      (nx_ip_raw_packet_processing.c) and never touches
 *      nx_ip_raw_received_packet_head.  So nx_ip_raw_packet_receive() becomes
 *      dead code, and the queue, the per-protocol demultiplex and the wakeup
 *      have to live here.
 *
 * The filter's return value decides who owns the packet: NX_SUCCESS means "I
 * took it" and the stack stops processing it, anything else means "not mine"
 * and normal dispatch continues.  Consuming would save one packet copy but
 * break the machine: an ICMP echo request claimed by a raw socket is an echo
 * request nobody answers, and an echo reply claimed by one is a reply
 * nx_icmp_ping() never wakes on.  So the filter takes a copy for each
 * interested descriptor and always declines, a tee, not an interception.
 * That is what makes bsdsocktest 132 (ping 127.0.0.1 from a raw socket) work:
 * the reply it waits for is generated by the ICMP layer, which still sees the
 * request.
 *
 * The filter is installed only while at least one raw descriptor exists, so a
 * machine with none pays a single NULL test per inbound packet, inside a
 * branch NetX Duo already had.
 *
 * An IPv4 read delivers a whole IP datagram, header included, as 4.4BSD does:
 * callers parse `(buf[0] & 0x0F) * 4` to find the ICMP header.  The IP header
 * is still physically in the buffer when the filter runs,
 * nx_ipv4_packet_receive.c only advances nx_packet_prepend_ptr past it and
 * leaves nx_packet_ip_header pointing at it, so the copy is taken with the
 * pointer wound back and the original restored before declining.
 *
 * An IPv6 read does not include the header, which is RFC 3542's rule and the
 * reason the two halves of the filter differ: the copy starts where the
 * prepend pointer already is.  nx_packet_copy() carries nx_packet_ip_header
 * over into the copy either way, so bsd_raw_source() still finds the peer.
 *
 * Transmit is the mirror image and is not header-included: the caller writes
 * the protocol payload (an ICMP message, say) and nxd_ip_raw_packet_send()
 * prepends the IP header with the socket's protocol, TTL and TOS.  That is
 * BSD's default too, IP_HDRINCL is the opt-in, and NetX Duo's core has no
 * equivalent (see docs/RESEARCH.md 17).
 *
 * An ICMPv6 transmit carries one more obligation: the checksum covers the
 * IPv6 pseudo-header, so it cannot be computed until the source address is
 * known, and the source address is chosen by the stack.  Both happen in
 * bsd_raw_send_v6() below, in that order, and the send then names the address
 * it chose so the two cannot disagree.
 *
 * The filter runs on the NetX Duo IP thread, which holds nx_ip_protection for
 * the whole of its event loop (nx_ip_thread_entry.c).  The registry and the
 * per-socket queues are guarded by that same mutex: a ThreadX mutex is
 * recursive for its owner, so the filter's own get/put nests harmlessly, and
 * an application task, which reaches here already adopted by ThreadX, is
 * excluded.  Nothing in this file blocks while holding it; a receiver that has
 * to wait releases the mutex first and suspends on the socket's own semaphore.
 *
 * SPDX-License-Identifier: MIT
 */

#include "bsdsocket_vectors.h"

#ifdef AMINETXDUO_IPV6
#include "nx_ip.h"
#include "nx_ipv6.h"
#endif

#include <proto/exec.h>

/*
 * How many datagrams one raw socket may hold un-read.
 *
 * Same budget as the UDP queue in socket.c, a queued datagram is a whole
 * NX_PACKET out of the one shared pool, but a quarter of the UDP allowance,
 * because a raw socket sees traffic it did not ask for by port and a careless
 * application can leave it filling.
 */
#define BSD_RAW_QUEUE_MIN        4
#define BSD_RAW_QUEUE_CEILING   16
#define BSD_RAW_POOL_SHARE      16      /* 1/N of the pool per socket        */

/* Bytes of IPv4 header we are prepared to wind back over (5..15 words). */
#define BSD_RAW_MAX_IPHDR       60

/* The fixed IPv6 header; extension headers sit behind it and are not read. */
#define BSD_RAW_IPV6_HDR        40

/*
 * Every open raw descriptor on the machine, in one list.
 *
 * Global rather than per base: the filter is an NX_IP-level callback with no
 * user pointer, so there is one of it for the whole stack and it must reach
 * every base's raw sockets. Guarded by nx_ip_protection, see the file
 * header.
 */
static AmiSocket *bsd_raw_list;
static ULONG      bsd_raw_installed;

/* ------------------------------------------------------------------ queue, */

static ULONG bsd_raw_queue_max(VOID)
{
    NX_PACKET_POOL *pool = netstack_pool();
    ULONG           queue;

    if (pool == NULL)
        return BSD_RAW_QUEUE_MIN;

    queue = pool->nx_packet_pool_total / BSD_RAW_POOL_SHARE;

    if (queue < BSD_RAW_QUEUE_MIN)
        queue = BSD_RAW_QUEUE_MIN;
    if (queue > BSD_RAW_QUEUE_CEILING)
        queue = BSD_RAW_QUEUE_CEILING;

    return queue;
}

/* Caller holds nx_ip_protection. */
static VOID bsd_raw_flush(AmiSocket *sock)
{
    while (sock->as_RawHead != NX_NULL)
    {
        NX_PACKET *packet = sock->as_RawHead;

        sock->as_RawHead = packet->nx_packet_queue_next;
        nx_packet_release(packet);
    }

    sock->as_RawTail  = NX_NULL;
    sock->as_RawCount = 0;
}

/* ----------------------------------------------------------------- filter, */

/*
 * The tee.  Called from _nx_ip_raw_packet_processing() for every inbound IP
 * packet, on the IP thread, with `protocol` already reduced to the plain IP
 * protocol number.  Always returns "not mine".
 */
static UINT bsd_raw_filter(NX_IP *ip_ptr, ULONG protocol, NX_PACKET *packet_ptr)
{
    NX_PACKET_POOL *pool;
    AmiSocket      *sock;
    ULONG           behind;
    ULONG           hdr_len;
    BOOL            is_v6;

    if (packet_ptr == NX_NULL || bsd_raw_list == NULL)
        return NX_NOT_SUCCESSFUL;

    is_v6 = FALSE;

#ifdef AMINETXDUO_IPV6
    if (packet_ptr->nx_packet_ip_version == NX_IP_VERSION_V6)
        is_v6 = TRUE;
    else
#endif
    if (packet_ptr->nx_packet_ip_version != NX_IP_VERSION_V4)
        return NX_NOT_SUCCESSFUL;

    /*
     * How far the IP header sits behind the payload. Zero means the receive
     * path never recorded one, so there is nothing to copy.
     */
    if (packet_ptr->nx_packet_ip_header == NX_NULL ||
        packet_ptr->nx_packet_prepend_ptr < packet_ptr->nx_packet_ip_header)
        return NX_NOT_SUCCESSFUL;

    behind = (ULONG)(packet_ptr->nx_packet_prepend_ptr -
                     packet_ptr->nx_packet_ip_header);

    if (is_v6)
    {
        /* Not wound back: IPv6 delivers the payload alone. The bound is what
           bsd_raw_source() needs to read the source out of. */
        if (behind < BSD_RAW_IPV6_HDR)
            return NX_NOT_SUCCESSFUL;

        hdr_len = 0;
    }
    else
    {
        if (behind == 0 || behind > BSD_RAW_MAX_IPHDR)
            return NX_NOT_SUCCESSFUL;

        hdr_len = behind;
    }

    pool = netstack_pool();
    if (pool == NULL)
        return NX_NOT_SUCCESSFUL;

    tx_mutex_get(&ip_ptr->nx_ip_protection, TX_WAIT_FOREVER);

    for (sock = bsd_raw_list; sock != NULL; sock = sock->as_RawNext)
    {
        NX_PACKET *copy = NX_NULL;
        UINT       status;

        if ((ULONG)sock->as_Protocol != protocol)
            continue;

        /* A datagram belongs to the family its socket was opened in. */
        if (((sock->as_Flags & ASF_INET6) != 0) != (is_v6 != FALSE))
            continue;

        if (sock->as_RawCount >= sock->as_RawMax)
            continue;                   /* the reader is not keeping up */

#ifdef AMINETXDUO_IPV6
        /*
         * ICMP6_FILTER, RFC 3542 3.2.  The type is the first byte of the
         * ICMPv6 message, which for a v6 packet is where prepend_ptr already
         * points, the copy below does not wind back over the IP header.
         * Filtering here rather than at recv() is the point of the option:
         * a blocked type never becomes a packet copy.
         */
        if (is_v6 && protocol == (ULONG)NX_PROTOCOL_ICMPV6 &&
            packet_ptr->nx_packet_append_ptr > packet_ptr->nx_packet_prepend_ptr)
        {
            ULONG icmp_type = (ULONG)packet_ptr->nx_packet_prepend_ptr[0];

            if ((sock->as_Icmp6Filter[icmp_type >> 5] &
                 (1UL << (icmp_type & 31))) == 0UL)
                continue;
        }
#endif

        /*
         * Wind back over the IP header for the duration of the copy, then
         * restore it exactly: this packet is declined, so the stack goes on to
         * process it and every pointer must be as it was.
         */
        packet_ptr->nx_packet_prepend_ptr -= hdr_len;
        packet_ptr->nx_packet_length      += hdr_len;

        status = nx_packet_copy(packet_ptr, &copy, pool, NX_NO_WAIT);

        packet_ptr->nx_packet_prepend_ptr += hdr_len;
        packet_ptr->nx_packet_length      -= hdr_len;

        if (status != NX_SUCCESS || copy == NX_NULL)
            continue;                   /* pool pressure; drop, as BSD does */

        copy->nx_packet_queue_next = NX_NULL;

        if (sock->as_RawTail != NX_NULL)
            sock->as_RawTail->nx_packet_queue_next = copy;
        else
            sock->as_RawHead = copy;

        sock->as_RawTail = copy;
        sock->as_RawCount++;

        if (sock->as_RawSemOk)
            tx_semaphore_put(&sock->as_RawSem);

        /* The ordinary wakeup, so WaitSelect() and SIGIO see it too. */
        bsd_event_post(sock, FD_READ);
    }

    tx_mutex_put(&ip_ptr->nx_ip_protection);

    return NX_NOT_SUCCESSFUL;
}

/* -------------------------------------------------------------- lifecycle, */

LONG bsd_raw_open(struct AmiSocketBase *base, AmiSocket *sock)
{
    NX_IP *ip = netstack_ip();
    UINT   status;

    if (ip == NULL)
        return bsd_fail(base, AMI_ENETDOWN);

    if (tx_semaphore_create(&sock->as_RawSem, (CHAR *)"AmiNetXDuo RAW", 0)
            != TX_SUCCESS)
        return bsd_fail(base, AMI_ENOBUFS);

    sock->as_RawSemOk = TRUE;
    sock->as_RawMax   = bsd_raw_queue_max();

    tx_mutex_get(&ip->nx_ip_protection, TX_WAIT_FOREVER);

    if (bsd_raw_installed == 0)
    {
        /*
         * The hook at the top of _nx_ip_dispatch_process() needs both the raw
         * service enabled (nx_ip_raw_ip_processing) and a filter installed.
         * Enable first, so there is no window in which the built-in queue,
         * which nothing will ever drain, could take a packet.
         */
        status = nx_ip_raw_packet_enable(ip);
        if (status != NX_SUCCESS && status != NX_ALREADY_ENABLED)
        {
            tx_mutex_put(&ip->nx_ip_protection);
            tx_semaphore_delete(&sock->as_RawSem);
            sock->as_RawSemOk = FALSE;
            return bsd_fail(base, bsd_errno_from_nx(status));
        }

        status = nx_ip_raw_packet_filter_set(ip, bsd_raw_filter);
        if (status != NX_SUCCESS)
        {
            nx_ip_raw_packet_disable(ip);
            tx_mutex_put(&ip->nx_ip_protection);
            tx_semaphore_delete(&sock->as_RawSem);
            sock->as_RawSemOk = FALSE;
            return bsd_fail(base, bsd_errno_from_nx(status));
        }
    }

    sock->as_RawNext = bsd_raw_list;
    bsd_raw_list     = sock;
    bsd_raw_installed++;

    tx_mutex_put(&ip->nx_ip_protection);

    return 0;
}

VOID bsd_raw_close(AmiSocket *sock)
{
    NX_IP      *ip = netstack_ip();
    AmiSocket **link;

    if ((sock->as_Flags & ASF_RAW) == 0)
        return;

    if (ip != NULL)
    {
        tx_mutex_get(&ip->nx_ip_protection, TX_WAIT_FOREVER);

        for (link = &bsd_raw_list; *link != NULL; link = &(*link)->as_RawNext)
        {
            if (*link == sock)
            {
                *link = sock->as_RawNext;

                if (bsd_raw_installed > 0)
                    bsd_raw_installed--;

                break;
            }
        }

        sock->as_RawNext = NULL;
        bsd_raw_flush(sock);

        /* Last one out takes the per-packet cost with it. */
        if (bsd_raw_installed == 0)
        {
            nx_ip_raw_packet_filter_set(ip, NX_NULL);
            nx_ip_raw_packet_disable(ip);
        }

        tx_mutex_put(&ip->nx_ip_protection);
    }
    else
    {
        /*
         * The stack is gone; the packets went with it. The registry is not the
         * stack's, though, it is a file-scope static that outlives any
         * NX_IP. Leaving this socket linked would hand the next bring-up a
         * list into freed memory and a bsd_raw_installed that never returns to
         * zero, which is the filter never being installed again. Forbid()
         * rather than nx_ip_protection: the mutex lives inside the NX_IP that
         * has just been freed.
         */
        Forbid();

        for (link = &bsd_raw_list; *link != NULL; link = &(*link)->as_RawNext)
        {
            if (*link == sock)
            {
                *link = sock->as_RawNext;

                if (bsd_raw_installed > 0)
                    bsd_raw_installed--;

                break;
            }
        }

        Permit();

        sock->as_RawHead  = NX_NULL;
        sock->as_RawTail  = NX_NULL;
        sock->as_RawCount = 0;
        sock->as_RawNext  = NULL;
    }

    if (sock->as_RawSemOk)
    {
        tx_semaphore_delete(&sock->as_RawSem);
        sock->as_RawSemOk = FALSE;
    }
}

/* ------------------------------------------------------------------- send, */

#ifdef AMINETXDUO_IPV6

/*
 * The ICMPv6 checksum, which RFC 4443 makes mandatory and RFC 3542 makes the
 * stack's job on a raw socket. It covers the pseudo-header, so the caller
 * cannot compute it: nothing above this line knows which of the machine's
 * addresses the packet will leave with.
 */
static VOID bsd_raw_icmpv6_checksum(NX_PACKET *packet, ULONG *source,
                                    ULONG *dest)
{
    UBYTE *icmp = packet->nx_packet_prepend_ptr;
    USHORT sum;

    if ((ULONG)(packet->nx_packet_append_ptr - icmp) < 4UL)
        return;

    icmp[2] = 0;
    icmp[3] = 0;

    /* The version decides how much of the pseudo-header goes into the sum:
       _nx_ip_checksum_compute() folds in four bytes of each address unless the
       packet says IPv6. The send path sets this again on its way out. */
    packet->nx_packet_ip_version = NX_IP_VERSION_V6;

    sum = _nx_ip_checksum_compute(packet, NX_PROTOCOL_ICMPV6,
                                  (UINT)packet->nx_packet_length,
                                  source, dest);
    sum = (USHORT)~sum;

    icmp[2] = (UBYTE)(sum >> 8);
    icmp[3] = (UBYTE)(sum & 0xFF);
}

/*
 * The source address is picked first and then named on the send, rather than
 * left to nxd_ip_raw_packet_send() to pick again: the checksum below is
 * computed over it, and a second independent choice could differ.
 * _nxd_ipv6_interface_find() is the stack's own RFC 6724 selection and is what
 * nx_icmp_ping6() uses for the same reason.
 *
 * An RFC 3542 PKTINFO, a bound address or a zone overrides that selection,
 * each being the caller having made the choice already, and in that order,
 * the cmsg was supplied for this datagram where the other two are standing
 * state. Because the choice happens here and the checksum after it, a named
 * source is the source the checksum covers.
 */
static LONG bsd_raw_send_v6(struct AmiSocketBase *base, AmiSocket *sock,
                            NX_IP *ip, NX_PACKET *packet, NXD_ADDRESS *dest,
                            ULONG protocol, UINT hops, ULONG tos, ULONG scope,
                            const BsdCmsgSource *src)
{
    NXD_IPV6_ADDRESS *source = NX_NULL;
    UINT              src_index = 0;
    UINT              status;
    BsdSourceKind     kind;

    if (src != NULL && src->cs_Have)
    {
        LONG index = bsd_cmsg_source_index(ip, src, TRUE);

        if (index < 0)
        {
            nx_packet_release(packet);
            return bsd_fail(base, AMI_EADDRNOTAVAIL);
        }

        src_index = (UINT)index;
        kind      = BSD_SOURCE_INDEX;
    }
    else
    {
        kind = bsd_source_select(sock, dest, scope, &src_index);
    }

    switch (kind)
    {
        case BSD_SOURCE_INDEX:
            source = &ip->nx_ipv6_address[src_index];
            break;

        case BSD_SOURCE_ROUTE:
            tx_mutex_get(&ip->nx_ip_protection, TX_WAIT_FOREVER);
            status = _nxd_ipv6_interface_find(ip, dest->nxd_ip_address.v6,
                                              &source, NX_NULL);
            tx_mutex_put(&ip->nx_ip_protection);

            if (status != NX_SUCCESS || source == NX_NULL)
            {
                nx_packet_release(packet);
                return bsd_fail(base, AMI_ENETUNREACH);
            }
            break;

        case BSD_SOURCE_UNREACH:
            nx_packet_release(packet);
            return bsd_fail(base, AMI_ENETUNREACH);

        case BSD_SOURCE_REFUSE:
        default:
            nx_packet_release(packet);
            return bsd_fail(base, AMI_EADDRNOTAVAIL);
    }

    if (protocol == (ULONG)NX_PROTOCOL_ICMPV6)
    {
        bsd_raw_icmpv6_checksum(packet, source->nxd_ipv6_address,
                                dest->nxd_ip_address.v6);
    }

    status = nxd_ip_raw_packet_source_send(ip, packet, dest,
                                           (UINT)source->nxd_ipv6_address_index,
                                           protocol, hops, tos);
    if (status != NX_SUCCESS)
    {
        nx_packet_release(packet);

        return bsd_fail(base,
                        (status == NX_IP_ADDRESS_ERROR ||
                         status == NX_NO_INTERFACE_ADDRESS)
                            ? AMI_ENETUNREACH
                            : bsd_errno_from_nx(status));
    }

    return 0;
}

#endif /* AMINETXDUO_IPV6 */

LONG bsd_raw_send_packet(struct AmiSocketBase *base, AmiSocket *sock,
                         NX_PACKET *packet, const NXD_ADDRESS *addr,
                         ULONG scope, const BsdCmsgSource *src)
{
    NX_IP        *ip     = netstack_ip();
    NX_PACKET    *handed = packet;
    NXD_ADDRESS   dest   = *addr;
    BsdSourceKind source;
    UINT          src_index = 0;
    UINT          status;
    ULONG         protocol = (ULONG)(sock->as_Protocol & 0xFF);
    UINT          ttl      = (UINT)(sock->as_Ttl & 0xFF);
    ULONG         tos      = (ULONG)(sock->as_Tos & 0xFF);

    /* RFC 3542 6.3, over IPV6_UNICAST_HOPS; IPv6 only, which is where
       bsd_cmsg_parse() already refuses it for an AF_INET socket. */
    if (src != NULL && src->cs_HaveHops)
        ttl = (UINT)src->cs_Hops;

#ifndef AMINETXDUO_IPV6
    /* No v6, so no zones; the parameter stays so there is one signature. */
    (VOID)scope;
#endif

    if (ip == NULL)
    {
        nx_packet_release(packet);
        return bsd_fail(base, AMI_ENETDOWN);
    }

#ifdef AMINETXDUO_IPV6
    if (dest.nxd_ip_version == NX_IP_VERSION_V6)
        return bsd_raw_send_v6(base, sock, ip, handed, &dest, protocol, ttl,
                               tos, scope, src);
#endif

    /*
     * IP_HDRINCL is translated rather than passed through.
     *
     * NetX Duo's core has no header-included raw transmit: every raw send goes
     * out through nxd_ip_raw_packet_send(), which builds the IP header itself
     * from a protocol, a TTL and a TOS. Refusing IP_HDRINCL on that basis cost
     * us traceroute, Roadshow's fails at startup with ENOPROTOOPT
     * (docs/RESEARCH.md 55).
     *
     * A caller that sets IP_HDRINCL is usually not asking for an arbitrary
     * header: traceroute wants to vary the TTL and the destination per probe,
     * two of the three fields the send call already takes. So the header the
     * caller wrote is parsed, its fields are mapped onto the call, and it is
     * stripped; NetX Duo then emits an equivalent header.
     *
     * What does not survive: IP options (the header is dropped whole, options
     * included), a chosen identification field, a chosen source address, the
     * DF/MF flags and fragment offsets, and any deliberately wrong checksum.
     * The version, IHL, total length and checksum are all recomputed.
     *
     * A short or implausible header is refused with EINVAL, as BSD does for a
     * header-included write it cannot parse.
     */
    if (sock->as_HdrIncl)
    {
        const UBYTE *hdr = (const UBYTE *)handed->nx_packet_prepend_ptr;
        ULONG        have = (ULONG)(handed->nx_packet_append_ptr -
                                    handed->nx_packet_prepend_ptr);
        ULONG        ihl;

        if (have < 20UL || (hdr[0] >> 4) != 4)
        {
            nx_packet_release(handed);
            return bsd_fail(base, AMI_EINVAL);
        }

        ihl = (ULONG)(hdr[0] & 0x0F) * 4UL;
        if (ihl < 20UL || ihl > have)
        {
            nx_packet_release(handed);
            return bsd_fail(base, AMI_EINVAL);
        }

        tos      = (ULONG)hdr[1];
        ttl      = (UINT)hdr[8];
        protocol = (ULONG)hdr[9];

        /*
         * The destination in the header wins over the one passed to sendto(),
         * which is what "the header is included" means. traceroute fills both
         * in agreement anyway.
         */
        dest.nxd_ip_version = NX_IP_VERSION_V4;
        dest.nxd_ip_address.v4 = ((ULONG)hdr[16] << 24) |
                                 ((ULONG)hdr[17] << 16) |
                                 ((ULONG)hdr[18] <<  8) |
                                  (ULONG)hdr[19];

        handed->nx_packet_prepend_ptr += ihl;
        handed->nx_packet_length      -= ihl;
    }

    /*
     * After the IP_HDRINCL parse, which can move the destination, and the
     * destination is what decides whether the bound address can reach it.
     */
    if (src != NULL && src->cs_Have)
    {
        LONG index = bsd_cmsg_source_index(ip, src, FALSE);

        if (index < 0)
        {
            nx_packet_release(handed);
            return bsd_fail(base, AMI_EADDRNOTAVAIL);
        }

        source    = BSD_SOURCE_INDEX;
        src_index = (UINT)index;
    }
    else
    {
        source = bsd_source_select(sock, &dest, 0UL, &src_index);
    }

    if (source == BSD_SOURCE_REFUSE || source == BSD_SOURCE_UNREACH)
    {
        nx_packet_release(handed);
        return bsd_fail(base, (source == BSD_SOURCE_UNREACH)
                                  ? AMI_ENETUNREACH
                                  : AMI_EADDRNOTAVAIL);
    }

    /*
     * The same test bsd_send_udp() makes, one header shorter, and made here
     * because IP_HDRINCL has by now taken the caller's header off and settled
     * the destination. Transmit fragmentation is available, src/netstack/
     * calls nx_ip_fragment_enable() for the receive side, and deliberately
     * not used here: a raw sender asking for more than the path carries wants
     * to be told so, which is what its ping or its traceroute probe is for.
     * IP options are not carried on this path, so 20 and 40 are exact.
     */
    {
        LONG  mtu      = bsd_route_mtu(ip, &dest);
        ULONG overhead = (dest.nxd_ip_version == NX_IP_VERSION_V6) ? 40UL : 20UL;

        if (mtu >= 0 && handed->nx_packet_length + overhead > (ULONG)mtu)
        {
            nx_packet_release(handed);
            return bsd_fail(base, AMI_EMSGSIZE);
        }
    }

    if (source == BSD_SOURCE_INDEX)
        status = nxd_ip_raw_packet_source_send(ip, handed, &dest, src_index,
                                               protocol, ttl, tos);
    else
        status = nxd_ip_raw_packet_send(ip, handed, &dest, protocol, ttl, tos);

    if (status != NX_SUCCESS)
    {
        /* The error-checking wrapper only clears the caller's pointer on
           success, so on failure the packet is still ours. */
        if (handed != NX_NULL)
            nx_packet_release(handed);

        return bsd_fail(base,
                        (status == NX_IP_ADDRESS_ERROR ||
                         status == NX_NO_INTERFACE_ADDRESS)
                            ? AMI_ENETUNREACH
                            : bsd_errno_from_nx(status));
    }

    return 0;
}

/* ---------------------------------------------------------------- receive, */

NX_PACKET *bsd_raw_receive(AmiSocket *sock, ULONG wait, UINT *why)
{
    NX_IP *ip = netstack_ip();

    /* Default to NX_NO_PACKET, so a caller that never looks at *why still
       gets the old behaviour rather than a stale status. */
    if (why != NULL)
        *why = NX_NO_PACKET;

    if (ip == NULL)
    {
        if (why != NULL)
            *why = NX_NOT_ENABLED;

        return NX_NULL;
    }

    for (;;)
    {
        NX_PACKET *packet;
        UINT       status;

        tx_mutex_get(&ip->nx_ip_protection, TX_WAIT_FOREVER);

        packet = sock->as_RawHead;
        if (packet != NX_NULL)
        {
            sock->as_RawHead = packet->nx_packet_queue_next;
            if (sock->as_RawHead == NX_NULL)
                sock->as_RawTail = NX_NULL;
            if (sock->as_RawCount > 0)
                sock->as_RawCount--;

            packet->nx_packet_queue_next = NX_NULL;
        }

        tx_mutex_put(&ip->nx_ip_protection);

        if (packet != NX_NULL)
        {
            /*
             * Keep the semaphore's count equal to the queue's depth. Without
             * this a non-blocking read would leave a credit behind and the
             * next blocking read would spin: get() would succeed at once,
             * find nothing queued, and go round again immediately.
             */
            if (sock->as_RawSemOk)
                (VOID)tx_semaphore_get(&sock->as_RawSem, TX_NO_WAIT);

            return packet;
        }

        if (wait == NX_NO_WAIT || !sock->as_RawSemOk)
            return NX_NULL;

        /* Outside the mutex, or the IP thread could never queue anything. */
        status = tx_semaphore_get(&sock->as_RawSem, wait);
        if (status != TX_SUCCESS)
        {
            /*
             * TX_WAIT_ABORTED means the thread was signalled and must not come
             * back as "try again"; the caller cannot tell the difference
             * otherwise. Third site in docs/RESEARCH.md 37.2.
             */
            if (why != NULL)
                *why = (status == TX_WAIT_ABORTED) ? NX_WAIT_ABORTED
                                                   : NX_NO_PACKET;

            return NX_NULL;
        }
    }
}

VOID bsd_raw_source(NX_PACKET *packet, NXD_ADDRESS *addr)
{
    const UBYTE *ip_hdr;
    ULONG        source = 0;

    bsd_addr_from_v4(addr, 0UL);

    if (packet == NX_NULL)
        return;

#ifdef AMINETXDUO_IPV6
    /*
     * An IPv6 datagram does not start at its header, so the source comes from
     * where nx_packet_copy() recorded it: bytes 8..23 of the fixed header.
     */
    if (packet->nx_packet_ip_version == NX_IP_VERSION_V6)
    {
        const UBYTE *v6_hdr = packet->nx_packet_ip_header;

        if (v6_hdr == NX_NULL ||
            (ULONG)(packet->nx_packet_prepend_ptr - v6_hdr) < BSD_RAW_IPV6_HDR)
            return;

        addr->nxd_ip_version = NX_IP_VERSION_V6;
        bsd_in6_to_words(&v6_hdr[8], addr->nxd_ip_address.v6);

        return;
    }
#endif

    /*
     * The datagram starts at its own IP header, see the file comment. The
     * source address is bytes 12..15, in network order, which on m68k is the
     * order it is wanted in.
     *
     * The bound is the first fragment's contiguous run, not nx_packet_length,
     * which covers the whole chain: a twenty-byte total says nothing about how
     * many of those bytes are at prepend_ptr. The pool's payload is far wider
     * than an IP header so this cannot bite today, but that assumption would
     * not survive a pool resize.
     */
    if ((ULONG)(packet->nx_packet_append_ptr -
                packet->nx_packet_prepend_ptr) < 20UL)
        return;

    ip_hdr = packet->nx_packet_prepend_ptr;

    source = ((ULONG)ip_hdr[12] << 24) | ((ULONG)ip_hdr[13] << 16) |
             ((ULONG)ip_hdr[14] <<  8) | (ULONG)ip_hdr[15];

    bsd_addr_from_v4(addr, source);
}

ULONG bsd_raw_available(AmiSocket *sock)
{
    ULONG length = 0;

    if (sock->as_RawHead != NX_NULL)
        nx_packet_length_get(sock->as_RawHead, &length);

    return length;
}
