/*
 * bsdsocket.library -- SOCK_RAW.
 *
 * WHY THIS IS NOT A WRAPPER AROUND nx_ip_raw_packet_receive()
 *
 * NetX Duo has no raw socket object.  It has an IP-level raw *service*: one
 * queue per NX_IP, fed by _nx_ip_raw_packet_processing(), drained by whoever
 * calls nx_ip_raw_packet_receive() first.  Two things make that unusable as
 * the back end for a BSD descriptor:
 *
 *   1. ICMP never reaches it.  _nx_ip_dispatch_process() sends ICMPv4 to
 *      nx_ip_icmp_packet_receive and only consults the raw hook in the "I do
 *      not recognise this protocol" branch, so a raw socket opened with
 *      IPPROTO_ICMP -- the one every ping and traceroute opens -- would never
 *      see a byte.  NX_ENABLE_IP_RAW_PACKET_ALL_STACK (port nx_user.h) moves
 *      the hook to the top of the dispatch, ahead of TCP, UDP, ICMP and IGMP.
 *
 *   2. That hook is the *filter*, and installing a filter turns the queue off
 *      entirely: _nx_ip_raw_packet_processing() returns as soon as it sees one
 *      (nx_ip_raw_packet_processing.c) and never touches
 *      nx_ip_raw_received_packet_head.  So nx_ip_raw_packet_receive() becomes
 *      dead code, and the queue, the per-protocol demultiplex and the wakeup
 *      have to live here.
 *
 * WE COPY AND DECLINE, WE DO NOT CONSUME
 *
 * The filter's return value decides who owns the packet: NX_SUCCESS means "I
 * took it" and the stack stops processing it, anything else means "not mine"
 * and normal dispatch continues.  Consuming would be cheaper by one packet
 * copy and would break the machine: an ICMP echo request claimed by a raw
 * socket is an echo request nobody answers, and an echo reply claimed by one
 * is a reply nx_icmp_ping() never wakes on.  So the filter takes a copy for
 * each interested descriptor and always declines, which makes it a tee rather
 * than an interception -- and makes bsdsocktest 132 (ping 127.0.0.1 from a
 * raw socket) work, because the reply it waits for is generated by the ICMP
 * layer that still sees the request.
 *
 * The filter is installed only while at least one raw descriptor exists, so a
 * machine with none pays a single NULL test per inbound packet, inside a
 * branch NetX Duo already had.
 *
 * WHAT A READER GETS
 *
 * A whole IP datagram, header included, exactly as 4.4BSD delivers a raw
 * read: the suite parses `(buf[0] & 0x0F) * 4` to find the ICMP header, and
 * so does every ping and traceroute ever written.  The IP header is still
 * physically in the buffer when the filter runs -- nx_ipv4_packet_receive.c
 * only advances nx_packet_prepend_ptr past it and leaves nx_packet_ip_header
 * pointing at it -- so the copy is taken with the pointer wound back and the
 * original restored before we decline.
 *
 * Transmit is the mirror image and is NOT header-included: the caller writes
 * the protocol payload (an ICMP message, say) and nxd_ip_raw_packet_send()
 * prepends the IP header with the socket's protocol, TTL and TOS.  That is
 * BSD's default too -- IP_HDRINCL is the opt-in, and NetX Duo's core has no
 * equivalent (see docs/RESEARCH.md 17).
 *
 * LOCKING
 *
 * The filter runs on the NetX Duo IP thread, which holds nx_ip_protection for
 * the whole of its event loop (nx_ip_thread_entry.c).  So the registry and the
 * per-socket queues are guarded by that same mutex: a ThreadX mutex is
 * recursive for its owner, so the filter's own get/put nests harmlessly, and
 * an application task -- which reaches here already adopted by ThreadX -- is
 * properly excluded.  Nothing in this file blocks while holding it; a
 * receiver that has to wait releases the mutex first and suspends on the
 * socket's own semaphore.
 *
 * SPDX-License-Identifier: MIT
 */

#include "bsdsocket_vectors.h"

#include <proto/exec.h>

/*
 * How many datagrams one raw socket may hold un-read.
 *
 * Same budget argument as the UDP queue in socket.c -- a queued datagram is a
 * whole NX_PACKET out of the one shared pool -- but tighter, because a raw
 * socket sees traffic it did not ask for by port and a careless application
 * can leave it filling.  A quarter of the UDP allowance.
 */
#define BSD_RAW_QUEUE_MIN        4
#define BSD_RAW_QUEUE_CEILING   16
#define BSD_RAW_POOL_SHARE      16      /* 1/N of the pool per socket        */

/* Bytes of IPv4 header we are prepared to wind back over (5..15 words). */
#define BSD_RAW_MAX_IPHDR       60

/*
 * Every open raw descriptor on the machine, in one list.
 *
 * It has to be global rather than per base: the filter is an NX_IP-level
 * callback with no user pointer, so there is exactly one of it for the whole
 * stack and it must be able to reach every base's raw sockets. Guarded by
 * nx_ip_protection -- see the file header.
 */
static AmiSocket *bsd_raw_list;
static ULONG      bsd_raw_installed;

/* ------------------------------------------------------------------ queue -- */

static ULONG bsd_raw_queue_max(VOID)
{
    NX_PACKET_POOL *pool = netstack_pool();
    ULONG           queue;

    if (pool == NULL)
        return BSD_RAW_QUEUE_MIN;

    queue = pool->nx_packet_pool_total / BSD_RAW_POOL_SHARE;

    if (queue < BSD_RAW_QUEUE_MIN)
        queue = BSD_RAW_QUEUE_MIN;
    if (queue > BSD_RAW_QUEUE_CEILING)
        queue = BSD_RAW_QUEUE_CEILING;

    return queue;
}

/* Caller holds nx_ip_protection. */
static VOID bsd_raw_flush(AmiSocket *sock)
{
    while (sock->as_RawHead != NX_NULL)
    {
        NX_PACKET *packet = sock->as_RawHead;

        sock->as_RawHead = packet->nx_packet_queue_next;
        nx_packet_release(packet);
    }

    sock->as_RawTail  = NX_NULL;
    sock->as_RawCount = 0;
}

/* ----------------------------------------------------------------- filter -- */

/*
 * The tee.  Called from _nx_ip_raw_packet_processing() for every inbound IP
 * packet, on the IP thread, with `protocol` already reduced to the plain IP
 * protocol number.  ALWAYS returns "not mine".
 */
static UINT bsd_raw_filter(NX_IP *ip_ptr, ULONG protocol, NX_PACKET *packet_ptr)
{
    NX_PACKET_POOL *pool;
    AmiSocket      *sock;
    ULONG           hdr_len;

    if (packet_ptr == NX_NULL || bsd_raw_list == NULL)
        return NX_NOT_SUCCESSFUL;

    /* IPv4 only. An AF_INET6 raw socket is not offered (see bsd_raw_open). */
    if (packet_ptr->nx_packet_ip_version != NX_IP_VERSION_V4)
        return NX_NOT_SUCCESSFUL;

    /*
     * How far the IP header sits behind the payload. Zero means the receive
     * path never recorded one, which is not something to guess about.
     */
    if (packet_ptr->nx_packet_ip_header == NX_NULL ||
        packet_ptr->nx_packet_prepend_ptr < packet_ptr->nx_packet_ip_header)
        return NX_NOT_SUCCESSFUL;

    hdr_len = (ULONG)(packet_ptr->nx_packet_prepend_ptr -
                      packet_ptr->nx_packet_ip_header);
    if (hdr_len == 0 || hdr_len > BSD_RAW_MAX_IPHDR)
        return NX_NOT_SUCCESSFUL;

    pool = netstack_pool();
    if (pool == NULL)
        return NX_NOT_SUCCESSFUL;

    tx_mutex_get(&ip_ptr->nx_ip_protection, TX_WAIT_FOREVER);

    for (sock = bsd_raw_list; sock != NULL; sock = sock->as_RawNext)
    {
        NX_PACKET *copy = NX_NULL;
        UINT       status;

        if ((ULONG)sock->as_Protocol != protocol)
            continue;

        if (sock->as_RawCount >= sock->as_RawMax)
            continue;                   /* the reader is not keeping up */

        /*
         * Wind back over the IP header for the duration of the copy, then put
         * it back exactly: we are declining this packet, so the stack goes on
         * to process it and every pointer must be as it was.
         */
        packet_ptr->nx_packet_prepend_ptr -= hdr_len;
        packet_ptr->nx_packet_length      += hdr_len;

        status = nx_packet_copy(packet_ptr, &copy, pool, NX_NO_WAIT);

        packet_ptr->nx_packet_prepend_ptr += hdr_len;
        packet_ptr->nx_packet_length      -= hdr_len;

        if (status != NX_SUCCESS || copy == NX_NULL)
            continue;                   /* pool pressure; drop, as BSD does */

        copy->nx_packet_queue_next = NX_NULL;

        if (sock->as_RawTail != NX_NULL)
            sock->as_RawTail->nx_packet_queue_next = copy;
        else
            sock->as_RawHead = copy;

        sock->as_RawTail = copy;
        sock->as_RawCount++;

        if (sock->as_RawSemOk)
            tx_semaphore_put(&sock->as_RawSem);

        /* And the ordinary wakeup, so WaitSelect() and SIGIO see it too. */
        bsd_event_post(sock, FD_READ);
    }

    tx_mutex_put(&ip_ptr->nx_ip_protection);

    return NX_NOT_SUCCESSFUL;
}

/* -------------------------------------------------------------- lifecycle -- */

LONG bsd_raw_open(struct AmiSocketBase *base, AmiSocket *sock)
{
    NX_IP *ip = netstack_ip();
    UINT   status;

    if (ip == NULL)
        return bsd_fail(base, AMI_ENETDOWN);

    if (tx_semaphore_create(&sock->as_RawSem, (CHAR *)"AmiNetXDuo RAW", 0)
            != TX_SUCCESS)
        return bsd_fail(base, AMI_ENOBUFS);

    sock->as_RawSemOk = TRUE;
    sock->as_RawMax   = bsd_raw_queue_max();

    tx_mutex_get(&ip->nx_ip_protection, TX_WAIT_FOREVER);

    if (bsd_raw_installed == 0)
    {
        /*
         * The hook at the top of _nx_ip_dispatch_process() needs BOTH: the raw
         * service enabled (nx_ip_raw_ip_processing) and a filter installed.
         * Enable first, so there is no window in which the built-in queue --
         * which nothing will ever drain -- could take a packet.
         */
        status = nx_ip_raw_packet_enable(ip);
        if (status != NX_SUCCESS && status != NX_ALREADY_ENABLED)
        {
            tx_mutex_put(&ip->nx_ip_protection);
            tx_semaphore_delete(&sock->as_RawSem);
            sock->as_RawSemOk = FALSE;
            return bsd_fail(base, bsd_errno_from_nx(status));
        }

        status = nx_ip_raw_packet_filter_set(ip, bsd_raw_filter);
        if (status != NX_SUCCESS)
        {
            nx_ip_raw_packet_disable(ip);
            tx_mutex_put(&ip->nx_ip_protection);
            tx_semaphore_delete(&sock->as_RawSem);
            sock->as_RawSemOk = FALSE;
            return bsd_fail(base, bsd_errno_from_nx(status));
        }
    }

    sock->as_RawNext = bsd_raw_list;
    bsd_raw_list     = sock;
    bsd_raw_installed++;

    tx_mutex_put(&ip->nx_ip_protection);

    return 0;
}

VOID bsd_raw_close(AmiSocket *sock)
{
    NX_IP      *ip = netstack_ip();
    AmiSocket **link;

    if ((sock->as_Flags & ASF_RAW) == 0)
        return;

    if (ip != NULL)
    {
        tx_mutex_get(&ip->nx_ip_protection, TX_WAIT_FOREVER);

        for (link = &bsd_raw_list; *link != NULL; link = &(*link)->as_RawNext)
        {
            if (*link == sock)
            {
                *link = sock->as_RawNext;

                if (bsd_raw_installed > 0)
                    bsd_raw_installed--;

                break;
            }
        }

        sock->as_RawNext = NULL;
        bsd_raw_flush(sock);

        /* Last one out takes the per-packet cost with it. */
        if (bsd_raw_installed == 0)
        {
            nx_ip_raw_packet_filter_set(ip, NX_NULL);
            nx_ip_raw_packet_disable(ip);
        }

        tx_mutex_put(&ip->nx_ip_protection);
    }
    else
    {
        /* The stack is gone; the packets went with it. */
        sock->as_RawHead  = NX_NULL;
        sock->as_RawTail  = NX_NULL;
        sock->as_RawCount = 0;
        sock->as_RawNext  = NULL;
    }

    if (sock->as_RawSemOk)
    {
        tx_semaphore_delete(&sock->as_RawSem);
        sock->as_RawSemOk = FALSE;
    }
}

/* ------------------------------------------------------------------- send -- */

LONG bsd_raw_send_packet(struct AmiSocketBase *base, AmiSocket *sock,
                         NX_PACKET *packet, const NXD_ADDRESS *addr)
{
    NX_IP      *ip     = netstack_ip();
    NX_PACKET  *handed = packet;
    NXD_ADDRESS dest   = *addr;
    UINT        status;

    if (ip == NULL)
    {
        nx_packet_release(packet);
        return bsd_fail(base, AMI_ENETDOWN);
    }

    status = nxd_ip_raw_packet_send(ip, handed, &dest,
                                    (ULONG)(sock->as_Protocol & 0xFF),
                                    (UINT)(sock->as_Ttl & 0xFF),
                                    (ULONG)(sock->as_Tos & 0xFF));

    if (status != NX_SUCCESS)
    {
        /* The error-checking wrapper only clears the caller's pointer on
           success, so on failure the packet is still ours. */
        if (handed != NX_NULL)
            nx_packet_release(handed);

        return bsd_fail(base,
                        (status == NX_IP_ADDRESS_ERROR ||
                         status == NX_NO_INTERFACE_ADDRESS)
                            ? AMI_ENETUNREACH
                            : bsd_errno_from_nx(status));
    }

    return 0;
}

/* ---------------------------------------------------------------- receive -- */

NX_PACKET *bsd_raw_receive(AmiSocket *sock, ULONG wait, UINT *why)
{
    NX_IP *ip = netstack_ip();

    /* NX_NO_PACKET is the "nothing queued" answer, so a caller that forgets
       to look still gets the old behaviour rather than a stale status. */
    if (why != NULL)
        *why = NX_NO_PACKET;

    if (ip == NULL)
    {
        if (why != NULL)
            *why = NX_NOT_ENABLED;

        return NX_NULL;
    }

    for (;;)
    {
        NX_PACKET *packet;
        UINT       status;

        tx_mutex_get(&ip->nx_ip_protection, TX_WAIT_FOREVER);

        packet = sock->as_RawHead;
        if (packet != NX_NULL)
        {
            sock->as_RawHead = packet->nx_packet_queue_next;
            if (sock->as_RawHead == NX_NULL)
                sock->as_RawTail = NX_NULL;
            if (sock->as_RawCount > 0)
                sock->as_RawCount--;

            packet->nx_packet_queue_next = NX_NULL;
        }

        tx_mutex_put(&ip->nx_ip_protection);

        if (packet != NX_NULL)
        {
            /*
             * Keep the semaphore's count equal to the queue's depth. Without
             * this a non-blocking read would leave a credit behind and the
             * next blocking read would spin: get() would succeed at once,
             * find nothing queued, and go round again immediately.
             */
            if (sock->as_RawSemOk)
                (VOID)tx_semaphore_get(&sock->as_RawSem, TX_NO_WAIT);

            return packet;
        }

        if (wait == NX_NO_WAIT || !sock->as_RawSemOk)
            return NX_NULL;

        /* Outside the mutex, or the IP thread could never queue anything. */
        status = tx_semaphore_get(&sock->as_RawSem, wait);
        if (status != TX_SUCCESS)
        {
            /*
             * TX_WAIT_ABORTED is a signalled thread and must not come back as
             * "try again" -- the caller cannot tell the difference otherwise,
             * which is docs/RESEARCH.md 37.2's third site.
             */
            if (why != NULL)
                *why = (status == TX_WAIT_ABORTED) ? NX_WAIT_ABORTED
                                                   : NX_NO_PACKET;

            return NX_NULL;
        }
    }
}

VOID bsd_raw_source(NX_PACKET *packet, NXD_ADDRESS *addr)
{
    const UBYTE *ip_hdr;
    ULONG        source = 0;

    bsd_addr_from_v4(addr, 0UL);

    if (packet == NX_NULL)
        return;

    /* The datagram starts at its own IP header -- see the file comment. The
       source address is bytes 12..15, in network order, which on m68k is the
       order it is wanted in. */
    if (packet->nx_packet_length < 20)
        return;

    ip_hdr = packet->nx_packet_prepend_ptr;

    source = ((ULONG)ip_hdr[12] << 24) | ((ULONG)ip_hdr[13] << 16) |
             ((ULONG)ip_hdr[14] <<  8) | (ULONG)ip_hdr[15];

    bsd_addr_from_v4(addr, source);
}

ULONG bsd_raw_available(AmiSocket *sock)
{
    ULONG length = 0;

    if (sock->as_RawHead != NX_NULL)
        nx_packet_length_get(sock->as_RawHead, &length);

    return length;
}
